<div class="home-content">
<div class="banner-section">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner')->toHtml(); ?></div>

<div class="home-page-block">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-block')->toHtml(); ?></div>
</div>
<div class="home-testimonial">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('testimonial')->toHtml(); ?></div>
</div>
</div>