<div class="about-content">
	<div class="banner-section">
	
	<?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-slider')->toHtml(); ?>



	</div>
	<div class="abt-video">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('about-us-2_1')->toHtml(); ?>
				<?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-us-2')->toHtml(); ?>
                <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-us-3')->toHtml(); ?>
                <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('home5')->toHtml(); ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('about-us-3')->toHtml(); ?>
                <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-us-4')->toHtml(); ?>
                <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-us-5')->toHtml(); ?>
                <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-us-6')->toHtml(); ?>
                <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('about-us-7')->toHtml(); ?>
        

	</div>
</div>
	