
<div class="home-content">
<div class="banner-section">
	<?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('news-hero-1')->toHtml(); ?>
</div>
<div class="home-page-label">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-page-label')->toHtml();?>
</div>
<div class="home-horizontal-rule">
</div>
<div class="blog-outer container">
<div class="blog-1">
<div class="">
	<?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('eahome3')->toHtml(); ?>
</div>
</div>
<div class="blog-1">
<div class="price">
	<?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('eahome4')->toHtml(); ?>
</div>
</div>
<div class="">
	<?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('spotlight')->toHtml(); ?>
</div>
<div class="met-gallery" id="artist-section">
<div class="gla-title-outer"><h2 class="glalery-title home-page-heading">New Artists</h2></div>
<ul class="bxslider1">
<?php
$collection = Mage::getModel('customer/customer')
        ->getCollection()
        ->addAttributeToSelect('*')
		->addAttributeToFilter('isapproved',1)
        ->addFieldToFilter('group_id', 3)
		->addAttributeToSort('created_at', 'DESC');
        $i=0;
		//echo"<pre>";print_r($collection->getData());echo"</pre>";
		foreach($collection  as $customer)
		{
			$i++;
			?>
			<?php if($i<25):?>
			<li>
                <?php $artistProfileURL = Mage::getModel('core/url_rewrite')->loadByIdPath('artist-profile-id-'.$customer->getentityId())->getRequestPath() ?>
				<?php if(strlen($artistProfileURL) > 0){?>
					<a href="<?php echo $this->getUrl().$artistProfileURL; ?>">
				<?php } else { ?>
					<a href="<?php echo $this->getUrl('custom/index/artist/id/'.$customer->getentityId()); ?>">
				<?php } ?>
                        
			<span><img alt="<?php echo "Artist: ".$customer->getName(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>customer<?php  echo $customer->getAvatar();?>" height="311px"; width="311px" /></span>
			<div class="pro-detls">
				<span class="meetUsers">Meet the Artist</span>
				<p><?php echo $customer->getName(); ?></p>
			</div>
			</a>
			</li>
		<?php endif;?>
		<?php } ?>

</ul>

</div>

<!--
<div class="catagory-product-outer met-gallery">
<div class="gla-title-outer"><h2 class="glalery-title">Recently Sold</h2></div>
<ul class="bxslider2">

<?php

$visibility = array(

	Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
	Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG

	);

	 $_productCollection= Mage::getResourceModel('reports/product_collection')
    ->addAttributeToSelect('*')
    ->addOrderedQty()
    ->addAttributeToFilter('visibility', $visibility)
    ->setOrder('created_at', 'desc');

	?>
<?php $i = 0;?>
							<?php foreach($_productCollection as $_product){?>

		<?php
						$protable= Mage::getSingleton('core/resource')->getTableName('marketplace_product');
						$sqlPaymentSystem1="SELECT * FROM ".$protable." WHERE mageproductid='".$_product->getId()."'";
						try {
						$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem1);
						$result1= $chkSystem->fetchall();
						}
						catch (Exception $e){
						 echo $e->getMessage();
						}

						foreach($result1 as $res){

						$artisid=$res['userid'];
						}
                         $artiscollection=Mage::getModel('customer/customer')->load($artisid);
		?>
					<?php
							$product=Mage::getModel('catalog/product')->load($_product->getId());
							$galid=$product->getGalcode();
                            if (!empty($galid)) {
                                 $customer =Mage::getModel('customer/customer')->load($galid);
 							     $galname=$customer->getGaleryname();
                            }

							?>
							<?php
							$tableName= Mage::getSingleton('core/resource')->getTableName('like_art');
							$sqlPaymentSystem1="SELECT * FROM ".$tableName." WHERE  proid='".$_product->getId()."'";
								try {
									$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem1);
									$like = $chkSystem->fetchall();
								}
								catch (Exception $e){
									 echo $e->getMessage();
								}
			       ?>

				   <?php
								$tableName= Mage::getSingleton('core/resource')->getTableName('follow_art');
								$sqlPaymentSystem1="SELECT * FROM ".$tableName." WHERE  artistid='".$_product->getId()."'";
									try {
										$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem1);
										$follow = $chkSystem->fetchall();
									}
									catch (Exception $e){
										 echo $e->getMessage();
									}
			       ?>


			<?php $i++;if($i<13)	{	?>
<li>
<a href="<?php echo $_product->getProductUrl(); ?>" title="View <?php echo $_product->getName(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(311,311); ?>" alt="Product image"  class="shadow" rel="black" />
<div class="pro-detls">
<ul>
<li class="one"><?php echo count($follow); ?></li>
<li class="two"><?php echo count($like); ?></li>
<li class="three">SOLD</li>
</ul>
<p class="artisname"><?php echo $artiscollection->getName(); ?></p>
<?php if (!empty($galid)) { ?>
    <p>Endorsed By:</p>
    <p style="margin-top: 3px;"><?php echo $galname; ?></p>
<?php } else { ?>
    <p> </p>
    <p style="margin-top: 3px;"> </p>
<?php } ?>
</div>
</a>
</li>
<?php }?>
<?php }?>
</ul>
</div>
    -->
</div>
<div class="secure-shipping">
  <?php echo  $this->getLayout()->createBlock('nwdrevslider/revslider')->setAlias('secure-shipping-guarantee')->toHtml(); ?>
</div>
</div>




<script type="text/javascript">
    jQuery(window).load(function(){


        jQuery(".bxslider").bxSlider({

            auto : true,
		    infiniteLoop: true,
            pager: true,
            nextSelector: ".cls-next",
	    prevSelector: ".cls-prev",

        });

		jQuery(".bxslider1").bxSlider({

            slideWidth: 315,
			minSlides: 3,
			maxSlides: 3,
			slideMargin: 24,
			infiniteLoop: true,

        });

		jQuery(".bxslider2").bxSlider({

            slideWidth: 315,
			minSlides: 3,
			maxSlides: 3,
			slideMargin: 24,
			infiniteLoop: true,

        });



    });
</script>
