<?php
$customerData = Mage::getSingleton('customer/session')->getCustomer();
//echo '<pre>';
//print_r($customerData);
$customerId = $customerData->getId();
$customeremail=$customerData->getEmail();
$galerycity=Mage::getResourceSingleton('customer/customer')->getAttribute('gallerycity')->getSource()->getAllOptions();
$galerycountry=Mage::getResourceSingleton('customer/customer')->getAttribute('gallerycountry')->getSource()->getAllOptions();
$galerystate=Mage::getResourceSingleton('customer/customer')->getAttribute('gallerystate')->getSource()->getAllOptions();
$galerypro=Mage::getResourceSingleton('customer/customer')->getAttribute('galprorepresent')->getSource()->getAllOptions();
$galerystyle=Mage::getResourceSingleton('customer/customer')->getAttribute('galstylrepresent')->getSource()->getAllOptions();
 ?>


<div class="page-title"><h3>Gallery Settings</h3></div>
<form action="<?php echo Mage::getBaseUrl() ?>customer/account/gallerprofilesave" method="post" autocomplete="off" id="galform" enctype="multipart/form-data">
<input type="hidden" value="<?php echo $customerId;?>" name="customerid">
<input type="hidden" value="<?php echo $customeremail;?>" name="customeremail">
<div class="promoter-pro-outer">
	<div class="outer-pro-img">
	<div class="promo-image">
			<ul class="form-list">
				<li  class="right-image">
				
					<?php if ($customerData->getSstechProfileimage()){ ?> 
							<div class="profileimage-wrapper">
								<img id="preview" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'customer'.$customerData->getSstechProfileimage();?>"/>
							</div>
					<?php } else{ ?>
					<img id="preview"/>
					<?php } ?>
				</li> 
				<li  class="left-file"> 
					<p>Upload a Square Image or it will be distorted <br/>200×200px at dpi Recommended</p>
					<div class="img-choosefile-outer">
						<span class="img-choosefile">Choose File</span>
						<input type="file" name="profileimage-file" id="file" onChange="readURL(this);"><br>
					</div>
				</li>   
			</ul>
	</div>
	<div class="make-chngs">Make Changes</div>
	<div class="promo-add">
		<ul>
			<li>
				<label class="required">Gallery Name</label>
				<input type="text" name="galeryname" class="required-entry" value="<?php echo $customerData->getGaleryname();?>"/>
			</li>
			<li>
				<label class="required">Gallery Phone</label>
				<input type="text" name="galleryphone" class="required-entry" value="<?php echo $customerData->getGalleryphone();?>"/>
			</li>
			<li>
				<label class="required">Gallery Email</label>
				<input type="text" name="galleryemail" class="required-entry" value="<?php echo  $customerData->getGalleryemail();?>"/>
			</li>
			<li>
				<label class="required">Gallery Website</label>
				<input type="text" name="gallerywebsite" class="required-entry" value="<?php echo $customerData->getGallerywebsite();?>"/>
			</li>
			<li>
				<label class="required">Gallery Address</label>
				<input type="text" name="galleryaddress" class="required-entry" value="<?php echo $customerData->getAddress();?>"/>
			</li>
			<li>
				<label class="required">Gallery City</label>
				<span id="city-selected" class="gla-select">Mumbai</span>
				<select id="city" class="city-select validate-select" name="city" onchange="javascript:document.getElementById('city-selected').innerHTML=this.options[this.selectedIndex].text;">
				<?php foreach ($galerycity as $option):?>
                      <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                     <?php endforeach;?>
				</select>
			</li>
			<li>
				<label class="required">Gallery State / Province</label>
				<span id="state-selected" class="gla-select validate-select">West bengal</span>
				<select name="state" id="state" onchange="javascript:document.getElementById('state-selected').innerHTML=this.options[this.selectedIndex].text;">
					<?php foreach ($galerystate as $option2):?>
                      <option value="<?php echo $option2['value'] ?>"<?php if ($option2['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option2['label'] ?></option>
                     <?php endforeach;?>
				</select>
			</li>
			<li>
				<label class="required">Gallery Zip / Postal Code</label>
				<input type="text" name="galleryzip" class="required-entry" value="<?php echo $customerData->getGalleryzip();?>"/>
			</li>
			<li>
				<label class="required">Gallery Country</label>
				<span id="country-selected" class="gla-select validate-select">Nepal</span>
				<select name="country" id="country" onchange="javascript:document.getElementById('country-selected').innerHTML=this.options[this.selectedIndex].text;">
					<?php foreach ($galerycountry as $option1):?>
                      <option value="<?php echo $option1['value'] ?>"<?php if ($option1['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option1['label'] ?></option>
                     <?php endforeach;?>
				</select>
			</li>
			
			
			
		</ul>
	</div>	
	</div>
	<div class="promo-des">
		<label>Gallery Description:</label>
		<textarea name="description" class="required-entry"><?php echo $customerData->getGalerydescription();?></textarea>
	</div>
	<div class="pro-repsnt">
		<ul>
			<li>
				<label class="class="required"">Types of Work your Gallery Deals (multiple selections)</label>
				<select name="productrepresent[]" multiple="multiple" class="validate-select" id="productrepresent">
				
					<?php foreach ($galerypro as $option5):?>
                      <option value="<?php echo $option5['value'] ?>"<?php if ($option5['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option5['label'] ?></option>
                     <?php endforeach;?>
			
				</select>
			</li>
			<li>
				<label class="class="required"">Styles Your Gallery Represents (multiple selections)</label>
				<select name="productstylerepresent[]" multiple="multiple" class="validate-select" id="productstylerepresent">
					<?php foreach ($galerystyle as $option6):?>
                      <option value="<?php echo $option6['value'] ?>"<?php if ($option6['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option6['label'] ?></option>
                     <?php endforeach;?>
				</select>
			</li>
		</ul>
	</div>
</div>
<div class="acnt-button-outer">
<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
</div>
</form>

<div class="questions">
<?php
 $tableName= Mage::getSingleton('core/resource')->getTableName('galery_qaadd');
 $answertable= Mage::getSingleton('core/resource')->getTableName('galery_qa');
$sqlPaymentSystem1="SELECT * FROM ".$tableName;
			try {
				$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem1);
				$result=$chkSystem->fetchall();
			}
			catch (Exception $e){
				 echo $e->getMessage();
			}
	?>
	<div class="qes-title"><?php echo count($result) ?> questions-profile page<a id="mckchange">Make Changes</a></div>
<form action="<?php echo Mage::getBaseUrl() ?>customer/account/galleryqa" method="post" autocomplete="off"  enctype="multipart/form-data">
<?php $i=0; ?>
	<?php foreach($result as $res){ $i++; ?>
	
	<?php
	$sqlPaymentSystem="SELECT * FROM ".$answertable." WHERE title='".$res['id']."' AND galeryid='".$customerId."'";
			try {
				$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem);
				$resultnew=$chkSystem->fetchall();
			}
			catch (Exception $e){
				 echo $e->getMessage();
			}
			foreach($resultnew as $resd){
				$answer=$resd['answer'];
				
			}
			?>
		
	<input type="hidden" value="<?php echo $customerId;?>" name="customerid">
	
	<input type="hidden" name="question[]" value="<?php echo $res['id']; ?>"/>
	<input type="hidden" name="questext-<?php echo $i; ?>" value="<?php echo $res['question']; ?>">
	<div class="qes-box">
	<?php echo $res['question'];  ?>
	<?php
	if($answer!=""){
		$disabled="disabled";
		
	} ?>
	<textarea name="answer-<?php echo $i; ?>" class="area" <?php echo $disabled; ?>><?php echo $answer; ?></textarea>
	</div>
    <?php } ?>
	<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>	
	</form>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {
		var city = <?php echo $customerData->getGallerycity();?>;
	var state = <?php echo $customerData->getGallerystate();?>;
	var country = <?php echo $customerData->getGallerycountry();?>;
	//alert(city);
	jQuery("#city option").filter(function() {
          return this.value == city; 
   }).prop('selected', true);
jQuery("#state option").filter(function() {
          return this.value == state; 
   }).prop('selected', true);
jQuery("#country option").filter(function() {
          return this.value == country; 
   }).prop('selected', true);
var product = [];
var style = [];
	  product = "<?php echo $customerData->getGalprorepresent();?>";
	  style = "<?php echo $customerData->getGalstylrepresent();?>";

jQuery("#productrepresent").val(product.split(','));
jQuery("#productstylerepresent").val(style.split(','));


});
</script>
<script type="text/javascript">
    $j = jQuery.noConflict();
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $j('#preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

</script>

<script type="text/javascript">
jQuery(document).ready(function(){
	
	jQuery("#mckchange").click(function(){
		
		jQuery(".area").removeAttr("disabled");
	});
	
});


</script>

<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('galform');
    //]]>
</script>