<div class="history-outer">
	<div class="hist-top">
		<h1>History</h1>
		<div class="hist-right">
			<ul>
				<li><a href="#">All</a></li>
				<li><a href="#">Liked Artwork</a></li>
				<li><a href="#">Endorsed Artwork</a></li>
				<li><a href="#">Message Arist</a></li>
				<li><a href="#">Following</a></li>
			</ul>
		</div>
	</div>
	<div class="hist-bottom">
		<div class="abut-hist">
			<ul>
				<li class="left">
					<img src="<?php echo $this->getskinUrl ("images/hist-img-1.jpg") ?>" alt=""/>
					<span class="title">Title</span>
				</li>
				<li class="right">
					<p>Liked<span>product1</span></p>
					<p>by<span>Test1</span></p>
					<p>on 5PM Thursday 17,June 2016</p>
				</li>
			</ul>
		</div>
		<div class="abut-hist">
			<ul>
				<li class="left">
					<img src="<?php echo $this->getskinUrl ("images/hist-img-2.jpg") ?>" alt=""/>
					<span class="title">Title</span>
				</li>
				<li class="right">
					<p>Endorsed<span>product1</span></p>
					<p>by<span>Test1</span></p>
					<p>on 5PM Thursday 17,June 2016</p>
				</li>
			</ul>
		</div>
		<div class="abut-hist">
			<ul>
				<li class="left">
					<img src="<?php echo $this->getskinUrl ("images/hist-img-3.png") ?>" alt=""/>
					<span class="title">Artis Name</span>
				</li>
				<li class="right">
					<p>started following<span>Test1</span></p>
					<p>on 5PM Thursday 17,June 2016</p>
				</li>
			</ul>
		</div>
		<div class="abut-hist">
			<ul>
				<li class="left">
					<img src="<?php echo $this->getskinUrl ("images/hist-img-3.png") ?>" alt=""/>
					<span class="title">Artis Name</span>
				</li>
				<li class="right">
					<p>Rejected request from<span>Test1</span></p>
					<p>on 5PM Thursday 17,June 2016</p>
				</li>
			</ul>
		</div>
		<div class="abut-hist">
			<ul>
				<li class="left">
					<img src="<?php echo $this->getskinUrl ("images/hist-img-3.png") ?>" alt=""/>
					<span class="title">Artis Name</span>
				</li>
				<li class="right">
					<p>Sent <a href="#">massage</a>to<span>Test1</span></p>
					<p>on 5PM Thursday 17,June 2016</p>
				</li>
			</ul>
		</div>
	</div>
</div>