<div class="met-gallery">
<h2>Meet the Gallery Owners - <span>more...</span></h2>
<ul>
<?php
$collection = Mage::getModel('customer/customer')
        ->getCollection()
        ->addAttributeToSelect('*')
        ->addFieldToFilter('group_id', 2);
        //$i=0;
	//	echo"<pre>";print_r($collection->getData());echo"</pre>";
		foreach($collection  as $customer)
		{
		
			?>
			
			<li>
			<p><?php echo $customer->getGaleryname();?></p>
			<span><a href="<?php echo $this->getUrl('custom/index/details/id/'.$customer->getentityId()); ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>customer<?php  echo $customer->getAvatar();?>" height="125px"; width="125px" /></a></span>
			
			<p class="name"><?php echo $customer->getFirstname(); ?>  <?php echo $customer->getLastname(); ?></p>
			</li>
		
		<?php } ?>

<ul>

</div>