<?php $customergroup = Mage::getSingleton('customer/session')->getCustomer()->getGroupId(); ?>
<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('Help Wiki') ?></h1>
    </div>
	<div class="page-body wiki-help-outer">
	<?php if($customergroup == 1){ ?>	
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('artist_wiki_block')->toHtml(); ?>
	<?php } elseif($customergroup == 2) { ?>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('director_wiki_block')->toHtml(); ?>
	<?php } ?>
	</div>
</div>
<script>

jQuery('body').on('click', '.down', function () {
	
	console.log(jQuery('#' + jQuery(this).attr('go')).position().top);
	var pos = jQuery('#' + jQuery(this).attr('go')).position().top - 80;
	console.log(pos);
	window.scrollTo(0,pos)
	
});
</script>