<?php
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$baseurl = Mage::getBaseUrl();
	$userId = $customer->getId();
	$subscription = Mage::getModel('customer/customer')->stripeApi($userId); // check user user subscription form stripe api
	$magentosubscription = Mage::getModel('customer/customer')->checkRecurring($userId); // check user user subscription from magento
	$cart = Mage::getModel('checkout/cart')->getQuote();
	foreach ($cart->getAllItems() as $item) {
		$productName = $item->getProduct()->getName();
		$productPrice = $item->getProduct()->getPrice();
		$productid=$item->getProduct()->getId();
	}
?>
<div class="membership">
    <div class="page-title page-title-membership">
        <h1><?php echo $this->__('Membership') ?></h1>
    </div>
	<div id="loader" class="cus-loader" style="display:none;">
		<div class="over-lay"></div>
		<div class="loader-body">
		</div>
	</div>
	<div class="account-message">
		<?php if($customer->getData('approval') == 65) { ?>
		<h2>Complete your <a href="<?php echo $baseurl."profile"; ?>">Profile</a> to Get Started.</h2>
		<?php } elseif($customer->getData('approval') == 64) { ?>
		<h2>We are currently reviewing your profile.</h2>
		<?php } else { ?>
			<?php if($magentosubscription['status'] == 2) { ?>
			<h2>Your Pro Membership is Not Active.</h2>
			<?php } elseif($magentosubscription['status'] == 1) { ?>
			<h2>Your Pro Membership is Active.</h2>
			<?php } elseif($magentosubscription['status'] == 3) { ?>
				<h2>Your Pro Membership is not active, images and submissions beyond your free 12 are hidden. <a href="<?php echo $baseurl."membership"; ?>">See Membership.</a></h2>
			<?php } ?>	
		<?php } ?>	
	</div>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('artist_membership_block_1')->toHtml(); ?>
	<div class="blue-heading-area">Plan Selection</div>
	<div class="sub-frm-outer">
		<?php $collectionVirtual = Mage::getResourceModel('catalog/product_collection')->addAttributeToFilter('type_id', array('eq' => 'virtual')); ?>
		<form name="subscription" id="subscription" method="POST" action="">
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
		<input type="hidden" name="customerid" value="<?php echo $userId;  ?>"/>
			<div class="sub-frm-inner-outer">
			<?php foreach($collectionVirtual as $key) { ?>
			<?php $product = Mage::getModel('catalog/product')->load($key->getId()); ?>
			<?php $url = Mage::getBaseUrl()."customer/account/redirect/?id=".$product->getId(); ?>
				<div class="sub-frm-inner1">
					<div class="sub-details">
						<div class="s-d-s1"><?php echo $product->getsubscriptionprice(); ?></div>
						<div class="s-d-s2">
							<?php echo $product->getName(); ?>
							<span class="description"><?php echo substr($product->getDescription(), 0, 100) ; ?></span>
						</div>
					</div>
					<div class="sub-name">
						<input type="radio" name="subtype" value="<?php echo $product->getId(); ?>" required <?php if($productid==$product->getId()) {?>checked<?php } elseif(empty($productid)) { ?>checked<?php }?>><span><?php echo $product->getDuration(); ?></span>
					</div>
				</div>
			<?php } ?>
			</div>	
			<div class="sub-frm-inner2">
				<input type="submit" name="submit" class="button mem-btn" id="submit" value="Continue" <?php if($customer->getData('approval') != 63) echo disabled?> >
			</div>
		</form>
	</div>
    <?php
        
?>

	<?php 
        $cart = Mage::getSingleton('checkout/cart');
        $cart->save();
        $count= $cart->getItemsCount();
    ?>

    <?php if($count!=0){ ?>
	<div id="heading-payment" class="blue-heading-area">Payment Information</div>
	

	
	<?php } ?>
</div>
<?php if($count!=0){ ?>
<script type="text/javascript">
jQuery('.loader-body').css({ top: '20%' });
jQuery("#loader").show();
jQuery(window).load(function(){
  jQuery('html, body').scrollTop(0);
  jQuery('html, body').scrollTop((jQuery("#heading-payment").offset().top - 150));
  //jQuery('html, body').animate({scrollTop: (jQuery("#heading-payment").offset().top - 60) }, 1000);
  jQuery("#loader").hide();
});

</script>
<div class="check-outer">
	
<iframe src="<?php echo $this->getBaseUrl() ?>onestepcheckout" id="chk" height="800" width="800"></iframe>

</div>
<?php } ?>

<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery(".mem-btn").click(function(){
		//alert("hi");
	jQuery("#loader").show();	
		
	});
	
});



</script>

