<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_Stripe
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 * @see Cryozonic_Stripe_Block_Payment_Info
 */

echo $this->escapeHtml($this->getMethod()->getTitle());

if ($_specificInfo = $this->getSpecificInformation()): ?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php if ($this->shouldDisplayStripeSection()): ?>
<table class="cryozonic payment-info">
	<?php if ($this->getInfo()->getCcType()): ?>
	<tr>
		<td><?php echo $this->getInfo()->getCcType(); ?> ending</td>
		<td>xxxx <?php echo $this->getInfo()->getCcLast4(); ?></td>
	</tr>
	<?php endif; ?>
    <tr>
        <td><?php echo $this->__('Radar Risk'); ?></td>
        <td class="result radar <?php echo $this->getRadarRisk(); ?>"><?php echo ucfirst($this->getRadarRisk()); ?></td>
    </tr>
	<tr>
		<td><?php echo $this->__('Street Check'); ?></td>
		<td class="result <?php echo $this->getStreetCheck(); ?>">
            <?php echo ucfirst($this->getStreetCheck()); ?>
            <img src="<?php echo $this->getSkinUrl('cryozonic_stripe/img/avs-passed.png'); ?>" class="passed">
            <img src="<?php echo $this->getSkinUrl('cryozonic_stripe/img/avs-failed.png'); ?>" class="failed">
        </td>
	</tr>
	<tr>
		<td><?php echo $this->__('Zip Check'); ?></td>
		<td class="result <?php echo $this->getZipCheck(); ?>">
            <?php echo ucfirst($this->getZipCheck()); ?>
            <img src="<?php echo $this->getSkinUrl('cryozonic_stripe/img/avs-passed.png'); ?>" class="passed">
            <img src="<?php echo $this->getSkinUrl('cryozonic_stripe/img/avs-failed.png'); ?>" class="failed">
        </td>
	</tr>
    <tr>
        <td><?php echo $this->__('Captured'); ?></td>
        <td class="captured"><?php echo $this->getCaptured(); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->__('Refunded'); ?></td>
        <td class="refunded"><?php echo $this->getRefunded(); ?></td>
    </tr>
    <?php if ($this->getPaymentId()): ?>
    <tr>
        <td><?php echo $this->__('Payment'); ?></td>
        <td class="payment">
            <a href="https://dashboard.stripe.com/payments/<?php echo $this->getPaymentId(); ?>" target="_blank">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
    <?php if ($this->getCustomerId()): ?>
    <tr>
        <td><?php echo $this->__('Customer'); ?></td>
        <td class="customer">
            <a href="https://dashboard.stripe.com/customers/<?php echo $this->getCustomerId(); ?>" target="_blank">View in Stripe</a>
        </td>
    </tr>
    <?php endif; ?>
</table>
<?php endif; ?>

<?php echo $this->getChildHtml()?>
