<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_StripeSubscriptions
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 */
?>
<?php if ($this->includeTax() && $this->showGrandTotal()):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php elseif ($this->showGrandTotal()): ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->getTotal()->getTitle() ?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php endif;?>
