<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_StripeSubscriptions
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 */
require_once 'Cryozonic/Stripe/lib/Stripe.php';

class Cryozonic_StripeSubscriptions_Model_Subscriptions extends Cryozonic_Stripe_Model_Standard
    implements Mage_Payment_Model_Recurring_Profile_MethodInterface
{
    const ADDON_NAME = "Stripe Subscriptions";
    const ADDON_VERSION = "2.0.1";
    const ADDON_URL = "https://store.cryozonic.com/magento-extensions/stripe-subscriptions.html";

    protected $_canManageRecurringProfiles = true;

    private $_rollback = array();
    private $_orderComments = array();

    public function __construct()
    {
        parent::__construct();

        $this->addOn($this::ADDON_NAME, $this::ADDON_VERSION);

        $this->useStoreCurrency = Mage::getStoreConfig('payment/cryozonic_stripe/use_store_currency');

        if ($this->isFrontEndSubscriptionPurchase())
        {
            Mage::helper('cryozonic_stripesubscriptions')->requireGuestLogin();
            $this->saveCards = $this->_hasRecurringProducts = true;
            $this->ensureStripeCustomer();
        }
    }

    public function assignData($data)
    {
        if ($this->hasRecurringProducts())
            $data['cc_save'] = 1;

        parent::assignData($data);

        if ($this->hasRecurringProducts())
        {
            if (!$this->getCustomerStripeId())
            {
                $this->ensureStripeCustomer();
            }

            if ($this->saveCards && !empty($data['cc_saved']) && $data['cc_saved'] != 'new_card')
            {
                $card = explode(':', $data['cc_saved']);
                $data['cc_saved'] = $card[0];

                $cu = $this->getStripeCustomer($this->getCustomerStripeId());
                if ($cu->default_source != $data['cc_saved'])
                {
                    $cu->default_source = $data['cc_saved'];
                    $cu->save();
                }
            }
        }

        return $this;
    }

    protected function hasRecurringProducts()
    {
        if ($this->_hasRecurringProducts)
            return true;

        $items = $this->getSessionQuote()->getAllItems();
        foreach ($items as $item)
        {
            if ($item->getProduct()->isRecurring())
                return $this->_hasRecurringProducts = true;
        }
        return $this->_hasRecurringProducts = false;
    }

    protected function isFrontEndSubscriptionPurchase()
    {
        return !Mage::app()->getStore()->isAdmin() && $this->hasRecurringProducts();
    }

    protected function isBackEndSubscriptionInvoiceCapture($payment)
    {
        return Mage::app()->getStore()->isAdmin()
            && Mage::helper('cryozonic_stripesubscriptions')->hasRecurringProducts($payment->getOrder()->getAllItems());
    }

    // Don't capture a second online payment when..
    protected function shouldProcessPayment($payment)
    {
        return
            // ..a recurring order event was generated by Stripe
            !Mage::helper('cryozonic_stripesubscriptions')->isRecurringOrder($payment->getOrder()) &&

            // ..a customer purchases a subscription and we automatically create an invoice
            !$this->isFrontEndSubscriptionPurchase() &&

            // ..an admin places an order from the back office which contains a single subscription product
            !$this->isBackEndSubscriptionPurchase() &&

            // ..an admin issued an invoice from the back office and tried to capture it online - not necessary because Stripe already charged the customer
            !$this->isBackEndSubscriptionInvoiceCapture($payment);
    }

    protected function isBackEndSubscriptionPurchase()
    {
        return Mage::app()->getStore()->isAdmin() && $this->hasRecurringProducts();
    }

    // When an order contains both a subscription and a virtual product,
    // magento does not set the correct order totals when spliting the order into two
    public function fixOrderWithVirtualProducts(&$payment, &$amount)
    {
        $order = $payment->getOrder();
        $quote = $order->getQuote();
        if ($quote->getVirtualItemsQty() > 0)
        {
            $order->setSubtotal($quote->getSubtotal());
            $order->setBaseSubtotal($quote->getBaseSubtotal());
            $order->setBaseSubtotalInclTax($quote->getBaseSubtotalInclTax());
            $order->setSubtotalInclTax($quote->getSubtotalInclTax());
            $order->setBaseGrandTotal($amount = $quote->getBaseGrandTotal());
            $order->setGrandTotal($quote->getGrandTotal());
        }
    }

    public function authorize(Varien_Object $payment, $amount)
    {
        if (!$this->shouldProcessPayment($payment))
            return $this;

        if ($amount == 0)
            $this->fixOrderWithVirtualProducts($payment, $amount);

        parent::authorize($payment, $amount);

        return $this;
    }

    public function capture(Varien_Object $payment, $amount)
    {
        if (!$this->shouldProcessPayment($payment))
            return $this;

        if ($amount == 0)
            $this->fixOrderWithVirtualProducts($payment, $amount);

        parent::capture($payment, $amount);

        return $this;
    }

    /**
     * Validate RP data
     *
     * @param Mage_Payment_Model_Recurring_Profile $profile
     */
    public function validateRecurringProfile(Mage_Payment_Model_Recurring_Profile $profile)
    {
        // Interval must be week, month or year
        // Mage::log('validateRecurringProfile');
    }

    /**
     * Submit RP to the gateway
     *
     * @param Mage_Payment_Model_Recurring_Profile $profile
     * @param Mage_Payment_Model_Info $paymentInfo
     */
    public function submitRecurringProfile(Mage_Payment_Model_Recurring_Profile $profile, Mage_Payment_Model_Info $paymentInfo)
    {
        // Mage::log('submitRecurringProfile');
        $customerStripeId = $this->getCustomerStripeId();

        // Verify coupon code if any
        $couponCode = $profile->getQuote()->getCouponCode();
        if ($couponCode)
        {
            try
            {
                if (\Stripe\Coupon::retrieve($couponCode))
                    $coupon = $this->usedCoupon = $couponCode;
            }
            catch (\Stripe\Error $e)
            {
                $this->log($e->getMessage());
            }
            catch (\Exception $e)
            {
                $this->log($e->getMessage());
            }

            if (empty($coupon))
            {
                $quote = $profile->getQuote();
                $quote->setData('coupon_code','')
                    ->setSubtotalWithDiscount($quote->getSubtotal())
                    ->setBaseSubtotalWithDiscount($quote->getBaseSubtotal())
                    ->save();
                $this->_orderComments[] = "<b>Error</b>: The customer tried to use coupon code $couponCode, but we could not retrieve it from Stripe.";
                $couponCode = null;
            }
        }

        // Create the order
        try
        {
            $order = $this->createOrder($profile);
            $profile->addOrderRelation($order->getId());
            $profile->save();
        }
        catch (\Exception $e)
        {
            $this->log("Error while trying to create an order for customer $customerStripeId: ".$e->getMessage());
            $this->rollback();
            $this->notifyTechnicalSupport('create_order_failed');
            Mage::throwException($this->t("The subscription process could not be completed."));
        }

        $quoteItemInfo = $profile->getQuoteItemInfo();
        $details = array(
            'product_id' => $quoteItemInfo->getProductId(),
            'price' => $quoteItemInfo->getPrice(),
            'qty' => $quoteItemInfo->getQty(),
            'billing_amount' => $profile->getBillingAmount(),
            'period_unit' => $profile->getPeriodUnit(),
            'period_frequency' => $profile->getPeriodFrequency(),
            'period_max_cycles' => $profile->getPeriodMaxCycles(),
            'start_datetime' => $profile->getStartDatetime(),
            'schedule_description' => $profile->getScheduleDescription(),
            'suspension_threshold' => $profile->getSuspensionThreshold(),
            'trial_period_unit' => $profile->getTrialPeriodUnit(),
            'trial_period_frequency' => $profile->getTrialPeriodFrequency(),
            'trial_period_max_cycles' => $profile->getTrialPeriodMaxCycles(),
            'trial_billing_amount' => $profile->getTrialBillingAmount(),
            'currency_code' => $profile->getCurrencyCode(),
            'shipping_amount' => 0,//$profile->getShippingAmount(),
            'tax_amount' => 0,//$profile->getTaxAmount(),
            'init_amount' => $profile->getInitAmount(),
            'order' => $order,
            'quote_item_info' => $quoteItemInfo
            );

        // Validate the billing period
        switch ($details['period_unit'])
        {
            case 'day':
            case 'week':
            case 'month':
            case 'year':
                break;
            default:
                $this->notifyTechnicalSupport('period_unit_wrong');
                Mage::throwException($this->t('Could not complete subscription because of an invalid billing period unit!'));
                break;
        }

        // Create a plan if it doesn't exist
        $planId = $this->generatePlanId($details);
        $plan = $this->getStripePlan($planId);
        if (!$plan) {
            $plan = $this->createStripePlan($details);
        }

        // Retrieve the customer object
        $customer = $this->getStripeCustomer($customerStripeId);
        if (!$customer && Mage::app()->getStore()->isAdmin())
        {
            // We get in here when trying to create a back office subscription order with
            // a customer that does not yet exist in our Stripe account.
            $customer = $this->createStripeCustomer();
            $data = $paymentInfo->getData();
            $this->saveCards = $data['cc_save'] = 1;
            $this->assignData($data);
        }
        else if (!$customer)
            Mage::throwException($this->t("The subscription process could not be completed."));
        $this->_rollback['customer'] = $customer;

        // Charge additional fees
        $ac = $this->getAmountCurrency($details);
        if ($ac['initial_fee'] && $ac['initial_fee'] > 0)
        {
            try
            {
                $params = array(
                    'customer' => $customer->id,
                    'amount' => $ac['initial_fee'],
                    'currency' => $ac['currency'],
                    'description' => 'Initial fee for order #'.$order->getRealOrderId()
                );
                $invoiceItem = \Stripe\InvoiceItem::create($params);
                $this->_rollback['invoice_item'] = $invoiceItem;
            }
            catch (\Stripe\Error $e)
            {
                $this->log("Error while trying to create invoice item: ".$e->getMessage());
                $this->rollback();
                Mage::throwException($this->t("The subscription process could not be completed."));
            }
            catch (\Exception $e)
            {
                $this->log("Error while trying to create invoice item: ".$e->getMessage());
                $this->rollback();
                Mage::throwException($this->t("The subscription process could not be completed."));
            }
        }

        // Subscribe the customer
        try
        {
            $trialDays = $this->getTrialDays($details);
            $subscription = $this->subscribeCustomer(
                    $customer,
                    $plan->id,
                    $ac['tax_percent'],
                    $trialDays,
                    $paymentInfo,
                    $couponCode
                );
            $this->_rollback['subscription'] = $subscription;
            $profile->setReferenceId($subscription->id);
            $profile->setState(Mage_Sales_Model_Recurring_Profile::STATE_ACTIVE);
            $profile->setCustomerId($order->getCustomerId());
            // $profile->setState(Mage_Sales_Model_Recurring_Profile::STATE_PENDING);
        }
        catch (\Stripe\Error\Card $e)
        {
            // Card declined etc errors
            $this->rollback();
            Mage::throwException($this->t($e->getMessage()));
        }
        catch (\Stripe\Error $e)
        {
            $this->checkError($e, $customer->id, $plan->id);
            $this->rollback();
            Mage::throwException($this->t($e->getMessage()));
        }
        catch (\Exception $e)
        {
            $this->checkError($e, $customer->id, $plan->id);
            $this->rollback();
            Mage::throwException($this->t($e->getMessage()));
        }

        try
        {
            // Invoice the order if necessary
            if (Mage::getStoreConfig("payment/cryozonic_stripesubscriptions/invoice_order") == Cryozonic_StripeSubscriptions_Model_Source_Invoice::AUTOMATIC && !$trialDays)
                Mage::helper('cryozonic_stripesubscriptions')->invoice($order);

            // Add a comment on the order about this subscription
            $comments = array();
            $comments[] = "Customer $customerStripeId has been subscribed to plan $planId.";

            // Make a note of any coupons used in this order
            $coupon = $this->usedCoupon; // Because __isset() is not implemented
            if (!empty($coupon))
                $comments[] = "Coupon code <b>$coupon</b> was used during the checkout for this order.";

            // Add any other comments
            if ($this->_orderComments)
                $comments = array_merge($comments, $this->_orderComments);


            if ($trialDays > 0)
            {
                $status = Mage_Sales_Model_Order::STATE_CLOSED;
                $comments[] = "<b>Order closed</b> because a trial period of $trialDays days exists and this is the initial order.";
            }
            else
            {
                // Set the order status
                $status = Mage::getStoreConfig('payment/cryozonic_stripesubscriptions/recurring_order_status');
                if (empty($status)) $status = Mage_Sales_Model_Order::STATE_COMPLETE;
            }

            $order->addStatusToHistory($status, implode(" ", $comments));

            $order->save();
            $order->sendNewOrderEmail();
        }
        catch (\Exception $e)
        {
            Mage::logException($e);
            $this->log("Could not change the order status: ".$e->getMessage());
        }

        // Dispatch an event to observers
        Mage::dispatchEvent('sales_order_place_after', array('order' => $order, 'subscribed' => true, 'customer_id' => $order->getCustomerId()));
    }

    private function checkError($e, $customerStripeId, $planId)
    {
        // Poor man's way of checking for the error code
        $message = $e->getMessage();
        if (preg_match('/with currency (\w+)$/', $message, $matches))
        {
            $currency = strtoupper($matches[1]);
            $this->rollback();
            Mage::throwException('Your account has been configured to use a different currency. Please complete the purchase in the currency: '.$currency);
        }

        $this->log("Error while trying to subscribe customer $customerStripeId to plan $planId: ".$e->getMessage());
        $this->log($e->getTraceAsString());
        $this->rollback();
        $this->notifyTechnicalSupport('subscribe_customer_failed');
        Mage::throwException($this->t("The subscription process could not be completed."));
    }

    protected function generatePlanId($details)
    {
        $ac = $this->getAmountCurrency($details);

        $pieces = array(
            $details['product_id'],
            $ac['currency'],
            $ac['amount'],
            strtoupper($details['period_unit']),
            $details['period_frequency']
        );

        return implode('-', $pieces);
    }

    protected function getStripePlan($planId)
    {
        try
        {
            return \Stripe\Plan::retrieve($planId);
        }
        catch (\Stripe\Error\InvalidRequest $e)
        {
            $this->log($e->getMessage());
        }
        return false;
    }

    protected function getTrialDays($details)
    {
        switch ($details['trial_period_unit']) {
            case null:
                $days = 0;
                break;
            case 'day':
                $days = $details['trial_period_frequency'];
                break;
            case 'week':
                $days = $details['trial_period_frequency'] * 7;
                break;
            case 'semi_month':
                $days = $details['trial_period_frequency'] * 14;
                break;
            case 'month':
                $days = $details['trial_period_frequency'] * 30;
                break;
            case 'year':
                $days = $details['trial_period_frequency'] * 356;
                break;
        }
        return round($days);
    }

    protected function getAmountCurrency($details)
    {
        $quoteItem = $details['quote_item_info'];

        if ($this->useStoreCurrency)
        {
            $price = $quoteItem->getPrice();
            $currency = $details['order']->getOrderCurrencyCode();
            $rate = $details['order']->getStoreToOrderRate(); // Exchange rate for multi-currency stores
            $shipping = $quoteItem->getShippingAmount();

            // Fix a multi-currency Magento issue
            if ($quoteItem->getPrice() == $quoteItem->getBasePrice() && $rate != 1)
            {
                if ($quoteItem->getOriginalCustomPrice())
                    $price = $quoteItem->getOriginalCustomPrice();
                else if ($quoteItem->getOriginalPrice())
                    $price = $quoteItem->getOriginalPrice();
                else
                    $price = round($quoteItem->getBasePrice() * $rate, 2);
            }
        }
        else
        {
            $price = $quoteItem->getBasePrice();
            $currency = $details['order']->getBaseCurrencyCode();
            $rate = 1;
            $shipping = $quoteItem->getBaseShippingAmount();
        }

        $cents = 100;
        if ($this->isZeroDecimal($currency))
            $cents = 1;

        $price_cents = round($price * $cents);
        $shipping_cents = round($shipping * $cents);

        // Older versions of Magento (e.g 1.6.2.0) do not convert the initial fee by exchange rate
        if (!empty($details['init_amount']) && is_numeric($details['init_amount']))
            $initial = (float)$details['init_amount'] * $cents * $rate;
        else
            $initial = 0;

        $qty = $quoteItem->getQty();

        // $qty has to be factored into the subscription price so that Stripe can
        // apply the tax_percent on the shipping amount too.
        $subscription_amount = ($price_cents * $qty) + $shipping_cents;

        return array(
            'amount' => $subscription_amount,
            'tax_percent' => $quoteItem->getTaxPercent(),
            'currency' => $currency,
            'initial_fee' => round($initial),
            'multiplier' => $cents
        );
    }

    protected function createStripePlan($details)
    {
        $planId = $this->generatePlanId($details);

        $this->log("Creating a new plan $planId");

        $ac = $this->getAmountCurrency($details);

        try
        {
            $params = array(
                "id" => $planId,
                "amount" => $ac['amount'], // == (price * qty) + shipping
                "currency" => $ac['currency'],
                "interval" => $details['period_unit'],
                "interval_count" => $details['period_frequency'],
                "name" => $details['schedule_description']
            );

            $response = \Stripe\Plan::create($params);

            return $response;
        }
        catch (\Stripe\Error $e)
        {
            $this->log("Could not set up customer profile: ".$e->getMessage());
            Mage::throwException($this->t('Could not set up customer profile: ').$this->t($e->getMessage()));
        }
        catch (\Exception $e)
        {
            $this->log("Could not set up customer profile: ".$e->getMessage());
            Mage::throwException($this->t('Could not set up customer profile: ').$this->t($e->getMessage()));
        }
    }

    protected function subscribeCustomer($customer, $planId, $tax_percent, $trialDays, Mage_Payment_Model_Info $info, $couponCode)
    {
        $params = array(
            "plan" => $planId,
            // "quantity" => $qty // We no longer set this because it has been factored into the total price at getAmountCurrency()
        );

        if ($couponCode)
            $params['coupon'] = $couponCode;

        // This may be card_ if a saved card was selected
        $token = $info->getAdditionalInformation('token');

        if ($this->saveCards && (strpos($token,'card_') === 0 || strpos($token,'src_') === 0))
        {
            $params['source'] = $token;
        }
        else if (strpos($token,'tok_') === 0)
        {
            // We should never get in here because all cards are saved
        }
        else
        {
            $card = array(
                "name" => $info->ccOwner,
                "number" => $info->ccNumber,
                "cvc" => $info->ccCid,
                "exp_month" => $info->ccExpMonth,
                "exp_year" => $info->ccExpYear
            );
            $params['source'] = $this->getAvsFields($card);
        }

        if ($tax_percent && $tax_percent > 0)
            $params['tax_percent'] = $tax_percent;

        if ($trialDays && $trialDays > 0)
            $params['trial_end'] = time() + $trialDays * 24 * 60 * 60;
        // else
        // {
        //     // We add a 1 minute trial period in case something goes sour
        //     // and we need to cancel the subscription. If we don't a payment
        //     // will go through which must be manually refunded.
        //     $params['trial_end'] = time() + 60;
        // }

        return $customer->subscriptions->create($params);
    }

    /**
     * Fetch RP details
     *
     * @param string $referenceId
     * @param Varien_Object $result
     */
    public function getRecurringProfileDetails($referenceId, Varien_Object $result)
    {
        // Mage::log('getRecurringProfileDetails');
    }

    /**
     * Whether can get recurring profile details
     */
    public function canGetRecurringProfileDetails()
    {
        // Mage::log('canGetRecurringProfileDetails');
        return false;
    }

    /**
     * Update RP data
     *
     * @param Mage_Payment_Model_Recurring_Profile $profile
     */
    public function updateRecurringProfile(Mage_Payment_Model_Recurring_Profile $profile)
    {
        // Mage::log('updateRecurringProfile');
    }

    /**
     * Manage status
     *
     * @param Mage_Payment_Model_Recurring_Profile $profile
     */
    public function updateRecurringProfileStatus(Mage_Payment_Model_Recurring_Profile $profile)
    {
        $customerStripeId = $this->getCustomerStripeId($profile->getCustomerId());
        $customer = $this->getStripeCustomer($customerStripeId);

        // This may happen if we delete the customer from Stripe but they are still subscribed to the plan in Magento
        if (!$customer)
            Mage::throwException($this->t("Could not update subscription because it has been deleted by an administrator."));

        $store = $this->getStore();
        $pauseResumeEnabled = $store->getConfig('payment/cryozonic_stripesubscriptions/pause_resume');

        switch($profile->newState)
        {
            case "suspended":
            case "canceled":
                try
                {
                    $subscription = $customer->subscriptions->retrieve($profile->referenceId);
                    if ($profile->newState == "suspended")
                    {
                        if (!$pauseResumeEnabled)
                            Mage::throwException("Sorry, pausing and resuming subscriptions is not allowed. You can only cancel this subscription.");
                        $quoteItemInfo = $profile->getOrderItemInfo();
                        $quoteItemInfo['cryozonic_stripesubscriptions_plan_id'] = $subscription->plan->id;
                        $quoteItemInfo['cryozonic_stripesubscriptions_remaining_period_time'] = $subscription->current_period_end - time();
                        $profile->setOrderItemInfo($quoteItemInfo);
                        $profile->save();
                    }
                    $subscription->cancel();
                }
                catch (\Stripe\Error\InvalidRequest $e)
                {
                    // We can get here when a Stripe Webhook triggered a customer.subscription.deleted event
                    // which means the subscription could not be found because it was deleted. Do nothing.
                }
                catch (\Exception $e)
                {
                    Mage::throwException($e->getMessage());
                }

                // Switch the customer to a different group
                $group = Mage::getStoreConfig("payment/cryozonic_stripesubscriptions/csgroup");
                Mage::helper('cryozonic_stripesubscriptions')->setCustomerGroup($group);

                break;

            case "active":
                if (!$pauseResumeEnabled)
                    Mage::throwException("Sorry, pausing and resuming subscriptions is not allowed. You can only cancel this subscription.");

                $quoteItemInfo = $profile->getOrderItemInfo();

                $params = array(
                    "plan" => $quoteItemInfo['cryozonic_stripesubscriptions_plan_id'], // We assume that the plan has not been deleted
                    "trial_end" => time() + $quoteItemInfo['cryozonic_stripesubscriptions_remaining_period_time']
                );

                try
                {
                    $subscription = $customer->subscriptions->create($params);
                    $startDate = new Zend_Date($params['trial_end'], Zend_Date::TIMESTAMP);
                    $profile->setReferenceId($subscription->id)
                        ->setNearestStartDatetime($startDate)
                        ->save();
                }
                catch (\Stripe\Error $e)
                {
                    $this->log('Could not activate customer subscription: ' . $e->getMessage());
                    Mage::throwException('Sorry, we could not activate this subscription!');
                }
                catch (\Exception $e)
                {
                    $this->log('Could not activate customer subscription: ' . $e->getMessage());
                    Mage::throwException('Sorry, we could not activate this subscription!');
                }

                // Assign the customer to a group
                $group = Mage::getStoreConfig("payment/cryozonic_stripesubscriptions/scgroup");
                Mage::helper('cryozonic_stripesubscriptions')->setCustomerGroup($group);

                break;
            default:
                break;
        }
    }

    private function createOrder($profile)
    {
        $quoteObj = $profile->getQuote();
        $item = $profile->getQuoteItemInfo();

        if ($quoteObj->getReservedOrderId())
            $quoteObj->unsReservedOrderId();

        $quoteObj->reserveOrderId();

        // Set payment method
        $quotePaymentObj = $quoteObj->getPayment(); // Mage_Sales_Model_Quote_Payment
        $quotePaymentObj->setMethod($this->_code);
        $quoteObj->setPayment($quotePaymentObj);

        // Convert quote to order
        $convertQuoteObj = Mage::getSingleton('sales/convert_quote');
        $orderObj = $convertQuoteObj->addressToOrder($quoteObj->getShippingAddress());
        $orderPaymentObj = $convertQuoteObj->paymentToOrderPayment($quotePaymentObj);

        // Convert quote addresses
        $orderObj->setBillingAddress($convertQuoteObj->addressToOrderAddress($quoteObj->getBillingAddress()));
        $orderObj->setShippingAddress($convertQuoteObj->addressToOrderAddress($quoteObj->getShippingAddress()));

        // Set payment options
        $orderObj->setPayment($convertQuoteObj->paymentToOrderPayment($quoteObj->getPayment()));

        $billing_amount = $shipping_amount = $tax_amount = 0;
        $base_billing_amount = $base_shipping_amount = $base_tax_amount = 0;

        // submitRecurringProfile() is called once per recurring profile so we should never create an order with the full set of ordered items.
        $qty = $item->getQty();

        // $items = $quoteObj->getAllItems();
        // foreach ($items as $item) {
            // @var $item Mage_Sales_Model_Quote_Item
            $orderItem = $convertQuoteObj->itemToOrderItem($item);

            $options = array();
            if ($productOptions = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct())) {
                $options = $productOptions;
            }
            if ($addOptions = $item->getOptionByCode('additional_options')) {
                $options['additional_options'] = unserialize($addOptions->getValue());
            }
            if ($options) {
                $orderItem->setProductOptions($options);
            }
            if ($item->getParentItem()) {
                $orderItem->setParentItem($orderObj->getItemByQuoteItemId($item->getParentItem()->getId()));
            }
            $orderObj->addItem($orderItem);

            $billing_amount += $orderItem->getPrice() * $qty;
            $base_billing_amount += $orderItem->getBasePrice() * $qty;
            $tax_amount += $orderItem->getTaxAmount();
            $base_tax_amount += $orderItem->getBaseTaxAmount();
        // }

        // The shipping amount is not on the order items so get it from the cart
        $shippingMethod = $quoteObj->getShippingAddress();
        // $items = $shippingMethod->getAllItems();
        // foreach ($items as $item) {
            $shipping_amount += $item->getShippingAmount();
            $base_shipping_amount += $item->getBaseShippingAmount();
        // }

        $couponCode = $quoteObj->getCouponCode();
        if (!empty($couponCode))
        {
            $discount_amount = Mage::helper('cryozonic_stripesubscriptions')
                ->getDiscountAmountFor($couponCode, $billing_amount + $shipping_amount);
            $base_discount_amount = Mage::helper('cryozonic_stripesubscriptions')
                ->getDiscountAmountFor($couponCode, $base_billing_amount + $base_shipping_amount);
        }
        else
        {
            $discount_amount = 0;
            $base_discount_amount = 0;
        }

        // Match Stripe's calculations so that shipping is included in both discount and tax calculations
        // These figures appear in the admin area and in the emails sent to the customer
        $item->setRowTotal($billing_amount + $shipping_amount);
        $item->setBaseRowTotal($base_billing_amount + $base_shipping_amount);

        $item->setRowTotalInclTax($item->getRowTotal() + $tax_amount);
        $item->setBaseRowTotalInclTax($item->getBaseRowTotal() + $base_tax_amount);

        $item->setRowTotalWithDiscount($item->getRowTotal() - $discount_amount);
        $item->setBaseRowTotalWithDiscount($item->getBaseRowTotal() - $discount_amount);

        $item->setNominalRowTotal($item->getRowTotal() + $tax_amount - $discount_amount);
        $item->setBaseNominalRowTotal($item->getBaseRowTotal() + $base_tax_amount - $base_discount_amount);

        $item->save();

        $orderInfo = $profile->getOrderInfo();
        $rate = $orderInfo['store_to_quote_rate'];
        $initAmount = $profile->getInitAmount() * $rate;
        $baseInitAmount = $profile->getInitAmount();

        $orderObj->setCanShipPartiallyItem(false)
            ->setBaseTaxAmount($base_tax_amount)
            ->setTaxAmount($tax_amount)
            ->setBaseShippingAmount($base_shipping_amount)
            ->setShippingAmount($shipping_amount)
            ->setBaseBillingAmount($base_billing_amount)
            ->setBillingAmount($billing_amount)
            ->setBaseSubtotal($base_billing_amount)
            ->setSubtotal($billing_amount)
            ->setDiscountAmount(-$discount_amount)
            ->setDiscountInvoiced(-$discount_amount)
            ->setBaseDiscountAmount(-$base_discount_amount)
            ->setBaseDiscountInvoiced(-$base_discount_amount)
            ->setDiscountTaxCompensation(0)
            ->setBaseGrandTotal($base_tax_amount + $base_shipping_amount + $base_billing_amount + $baseInitAmount - $discount_amount)
            ->setGrandTotal($tax_amount + $shipping_amount + $billing_amount + $initAmount - $base_discount_amount);

        // We need this in case we are dealing with a coupon code that has been deleted from Stripe
        if ($discount_amount == 0)
            $orderObj->setDiscountDescription(null);

        // Reduce inventory of product
        Mage::getSingleton('cataloginventory/stock')->registerItemSale($orderItem);

        $orderObj->save();

        return $orderObj;
    }

    private function rollback()
    {
        if (empty($this->_rollback) || empty($this->_rollback['customer']))
            return;

        $customer = $this->_rollback['customer'];

        if (!empty($this->_rollback['subscription']))
        {
            $sid = $this->_rollback['subscription']->id;
            $this->log("Rolling back subscription $sid");
            try
            {
                $this->_rollback['subscription']->cancel();
            }
            catch (\Stripe\Error $e)
            {
                $this->log("Rolling back subscription $sid failed: ".$e->getMessage());
            }
            catch (\Exception $e)
            {
                $this->log("Rolling back subscription $sid failed: ".$e->getMessage());
            }
        }

        if (!empty($this->_rollback['invoice_item']))
        {
            $this->_rollback['invoice_item']->delete();
        }
    }

    private function notifyTechnicalSupport($code)
    {

    }

    public function printTrace()
    {
        $e = new Exception();
        Mage::log($e->getTraceAsString());
    }

    public function log($msg)
    {
        // $this->printTrace();
        Mage::log("Stripe Subscriptions - ".$msg);
    }

    public function showSaveCardOption()
    {
        if ($this->hasRecurringProducts())
            return true;

        return ($this->saveCards && !$this->isGuest());
    }
}
