<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_StripeSubscriptions
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 */
?>
<?php
/**
 * @see Mage_Checkout_Block_Total_Nominal
 */
?>
<tr>
    <th colspan="<?php echo $this->getColspan() + 1; ?>" style="<?php echo $this->getTotalStyle() ?>" class="a-right">
        <?php echo sprintf(($this->getRenderingArea() == $this->getTotalArea()) ? '<strong>%s</strong>' : '%s', $this->escapeHtml($this->getTotalTitle())) ?>
    </th>
</tr>
<?php foreach ($this->getTotalItems() as $i => $item): ?>
<?php foreach ($this->getTotalItemDetails($item) as $j => $row):?>
<tr class="summary-details <?php echo "summary-details-nominal-{$i}" . (0 == $j ? ' summary-details-first' : '') . ($this->getItemDetailsRowIsCompounded($row) ? '' : ' summary-details-excluded')?>">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotalStyle() ?>" class="a-right">
        <?php echo $this->escapeHtml($this->getItemDetailsRowLabel($row)) ?>
    </td>
    <td class="a-right">
        <?php echo $this->formatPrice($this->getItemDetailsRowAmount($row)) ?>
    </td>
</tr>
<?php endforeach; ?>
<?php if ($this->getCouponCode()): ?>
<tr class="summary-details summary-details-nominal-<?php echo $i; ?>">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotalStyle() ?>" class="a-right">
        <?php echo $this->__('Discount'); ?> (<?php echo $this->getCouponCode(); ?>)
    </td>
    <td class="a-right">
        -<?php echo $this->formatPrice($this->getDiscountAmount($item)) ?>
    </td>
</tr>
<?php endif; ?>
<tr class="summary-total show-details" onclick="expandDetails(this, '<?php echo ".summary-details-nominal-{$i}"?>')">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotalStyle() ?>">
        <div class="summary-collapse"><?php echo $this->escapeHtml($this->getItemName($item)); ?></div>
    </td>
    <td class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getItemRowTotal($item) - $this->getDiscountAmount($item)) ?>
    </td>
</tr>
<?php endforeach; ?>
