<?php
/**
 * Create account form template
 * 
 * @category    design
 * @package     base_default
 * @author      Clarion Magento Team
 */
?>
<?php
/**
 * edit account form template
 *
 * @var $this Mage_Customer_Block_form_edit
 */
?>
<?php
$data=Mage::getSingleton('customer/session')->getCustomer();
$customerData = Mage::getSingleton('customer/session')->getCustomer();

$customerId = $customerData->getId();
$customer = Mage::getModel('customer/customer')->load($customerId);
$customerGroupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
?>
<div class="page-title">
    <h1><?php echo $this->__('Profile Settings') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off" enctype="multipart/form-data" onsubmit=" return minCheck()">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend account-cstm-title"><?php echo $this->__('Account Information') ?></h2>
		<div class="outer-imgbox">
			<?php  $customer->getAvatar();  ?>
			<?php if($customer->getAvatar()==""){ ?>
			
			<?php if($customerGroupId == 2){ ?>
			<span class="customer-img"><img id="preview2" src="<?php echo $this->getskinUrl() ?>images/nopropimg.png" height="125px"; width="125px"/></span>
			<?php } else { ?>
			<span class="customer-img"><img id="preview2" src="<?php echo $this->getskinUrl() ?>images/nopropimgart.png" height="125px"; width="125px"/></span>
            <?php } ?>
          <?php } else { ?>
			<span class="customer-img"><img id="preview2" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>customer<?php  echo $customer->getAvatar();?>" height="125px"; width="125px" /></span>
			<?php } ?>
			<ul class="prof-img">
				<li><span class="requer-cstm">*</span>Change your profile image </li>
				<li class="fields">
					<div class="input-box">
						<div class="img-choosefile-outer">
							<label for="avatar" class="img-choosefile-astm">Click here</label>
							<input type="file" name="avatar" onChange="readURL(this);" title="<?php echo $this->__('Avatar') ?>" id="avatar" class="input-text <?php if($customer->getAvatar()=="") {?>required-entry<?php } ?>" />
						</div>
					</div>
				</li>
			</ul>
		</div>	
		<div class="login-seeting-outer">		
			<p class="login-seting-title"><span class="requer-cstm">*</span>Login Settings (private)</p>
			<ul class="form-list">
				
				<li class="fields">
					<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
				</li>
				<li class="log-email">
					<!--<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>-->
					<div class="input-box">
						<input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
					</div>
				</li>
			<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
			<?php if ($_dob->isEnabled()): ?>
				<li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
			<?php endif ?>
			<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
			<?php if ($_taxvat->isEnabled()): ?>
				<li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
			<?php endif ?>
			<?php //$_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
			<?php //if ($_gender->isEnabled()): ?>
				<!--li><?php //echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li-->
			<?php //endif ?>
				<li class="control">
					<input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
				</li>
			</ul>
		</div>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend c-pass-title"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <!-- custom attributes -->
	<?php if ($customerGroupId == 1) { ?>
	<div class="fieldset">
		<h2 class="legend"><?php echo $this->__('Public Profile') ?></h2>
		<ul class="form-list">
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Address:" title="Address" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('address')) ?>" class="input-text" name="address" id="address" />
					</div>
				</div>
			</li>
			<li class="fields cstm-select-outer">
				<div class="field">
					<div class="input-box">
						<select name="country" id="country" class="input-text required-entry" onchange="getState(this.options[this.selectedIndex].getAttribute('country_code'))">
							<option value=""></option>
							<?php $options = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false);?>
							<?php foreach($options as $key): ?>
								<option country_code="<?php echo $key['value']; ?>" value="<?php echo $key['label'] ?>"<?php if($key['label']==$this->getCustomer()->getData('country')){?> selected <?php } ?>>
									<?php echo $key['label'] ?>
								</option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</li>
			<li class="fields cstm-select-outer" >
				<div class="field" id="append_state">
					<div class="input-box">
						<input type="text" placeholder="" title="State" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('state')) ?>" class="input-text required-entry" name="state" id="state" />
					</div>					
				</div>
			</li>
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="City:" title="City" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('city')) ?>" class="input-text required-entry" name="city" id="city" />
					</div>
				</div>
			</li>
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Zip code:" title="Zip code" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('zip_code')) ?>" class="input-text required-entry " name="zip_code" id="zip_code" />
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Phone:" title="Phone" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('phone')) ?>" class="input-text required-entry " name="phone" id="phone" />
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Website:" title="Website" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('website')) ?>" class="input-text validate-url" name="website" id="website" />
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Instagram URL:" title="Instagram URL" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('instagram_url')) ?>" class="input-text validate-url" name="instagram_url" id="instagram_url" />
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Facebook URL:" title="Facebook URL" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('facebook_url')) ?>" class="input-text validate-url" name="facebook_url" id="facebook_url" />
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Twitter URL:" title="Twitter URL" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('twitter_url')) ?>" class="input-text validate-url" name="twitter_url" id="twitter_url" />
					</div>
				</div>
			</li>			
			<!--li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Youtube Video Share Link:" title="Youtube Video Share Link" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('youtube_link')) ?>" class="input-text" name="youtube_link" id="youtube_link" onfocusout="validateYTVideo(event)"/>
						<div style="" id="validation_link_yt_video" class="validation-advice" style="display: inline-block"></div>
						<img id="img-yt_video-url-loader" src="<?php echo $this->getskinUrl() ?>images/ajax-loader.gif" alt="" style="height: 21px;margin-top: 10px;float: left;display:none"/>
						<input type="hidden" id="is-yt-video-url-valid" value="false"/>						
					</div>
				</div>
			</li-->			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<textarea class=" textarea" placeholder="Biography, Education, etc" cols="15" rows="2" title="Information about what you’re looking for" name="education" id="education"><?php echo $this->getCustomer()->getData('education'); ?></textarea>
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<textarea class=" textarea" placeholder="Clients:" cols="15" rows="2" title="Information about what you’re looking for" name="clients" id="clients"><?php echo $this->getCustomer()->getData('clients'); ?></textarea>
					</div>
				</div>
			</li>	
			<li class="fields" style="margin-left:0px">
				<div class="tooltip-outer tool-full">
					<span class="intergotive-sign"  style="margin-left:0px">Read why setting your criteria correctly is important</span>
					<div class="tooltip" style="display:none">Selecting your profession places all of your images under the correct category in the main image search. - Selecting the correct Type and Genre matches you with Art Directors who hire your type of work. *Take your time and carefully add the categories that best describe what you do.</div>					
				</div>
			</li>			
			<li class="fields cstm-select-outer">
				<div class="field">
					<label for="user_type" class=""><em></em><?php echo $this->__('What I do:') ?></label>
					<div class="input-box">
						<select name="profession" id="profession" class="input-text required-entry" >
							<option value=""></option>
							<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('profession')->getSource()->getAllOptions();?>
							<?php foreach($options as $key): ?>
								<?php if(!empty($key["value"])) { ?>
								<option value="<?php echo $key['value'] ?>"<?php if($key['value']==$this->getCustomer()->getData('profession')){?> selected <?php } ?>>
									<?php echo $key['label'] ?>
								</option>
								<?php }?>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</li>
			<li class="fields" <?php if($customerData->getData("profession") == 38 or empty($customerData->getData("profession"))) echo "style='display:none'"; ?> id="ph35">
				<div class="field">
					<label for="work_type_use_for_photography" class="type-of-work"><em></em><?php echo $this->__('Select 18 Categories:&nbsp;&nbsp;') ?></label><label class="how_many_selected_profile_page" id="label_hire_photography_selected"></label>
                    <div class="validation-advice" style="display:none" id="minpho">Please select 18 Categories.</div>
					<div class="input-box">
						<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('work_type_use_for_photography')->getSource()->getAllOptions();?>
						<ul class="custom-checkbox">
						<?php foreach ($options as $option):?>
							<?php if($option["value"] != "") { ?>
							<li><input type="checkbox" value="<?php echo $option['value'] ?>" name="work_type_use_for_photography[]" <?php if (in_array($option['value'], explode(',', $this->getCustomer()->getData('work_type_use_for_photography')))) echo "checked" ?> class="ph_checked"><span class="chaked-mark"></span><?php echo $option['label'] ?></li>
							<?php } ?>
						<?php endforeach;?>	
						</ul>
					</div>
				</div>
			</li>			
			<li class="fields" <?php if($customerData->getData("profession") == 35 or empty($customerData->getData("profession"))) echo "style='display:none'"; ?> id="il38">
				<div class="field">
					<label for="work_type_use_for_illustration" class="type-of-work"><em></em><?php echo $this->__('Select 18 Categories:&nbsp;&nbsp;') ?></label><label class="how_many_selected_profile_page" id="label_hire_illustrators_selected"></label>
                    <div class="validation-advice" style="display:none" id="minill">Please select 18 Categories.</div>
					<div class="input-box">
						<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('work_type_use_for_illustration')->getSource()->getAllOptions();?>
						<ul class="custom-checkbox">
						<?php foreach ($options as $option):?>
							<?php if($option["value"] != "") { ?>
							<li><input type="checkbox" value="<?php echo $option['value'] ?>" name="work_type_use_for_illustration[]" <?php if (in_array($option['value'], explode(',', $this->getCustomer()->getData('work_type_use_for_illustration')))) echo "checked" ?> class="il_checked"><span class="chaked-mark"></span><?php echo $option['label'] ?></li>
							<?php } ?>
						<?php endforeach;?>	
						</ul>
					</div>
				</div>
			</li>
			<li class="fields cstm-select-outer">
				<div class="field">
					<label for="gender" class="required"><em>*</em><?php echo $this->__('Gender:') ?></label>
					<div class="input-box">
						<select name="gender_new" id="gender" class="input-text required-entry" >
							<option value="">Select One</option>
							<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender_new')->getSource()->getAllOptions();?>
							<?php foreach($options as $key): ?>
								<?php if(!empty($key["value"])) { ?>
								<option value="<?php echo $key['value'] ?>"<?php if($key['value']==$this->getCustomer()->getData('gender_new')){?> selected <?php } ?>>
									<?php echo $key['label'] ?>
								</option>
								<?php }?>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</li>			
			<li class="fields cstm-select-outer">
				<div class="field">
					<label for="ethnicity" class="ethnicity-label required"><em>*</em><?php echo $this->__('Ethnicity:') ?></label>
					<div class="input-box">
						<select name="ethnicity" id="ethnicity" class="input-text required-entry" >
							<option value="">Select One</option>
							<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('ethnicity')->getSource()->getAllOptions();?>
							<?php foreach($options as $key): ?>
								<?php if(!empty($key["value"])) { ?>
								<option value="<?php echo $key['value'] ?>"<?php if($key['value']==$this->getCustomer()->getData('ethnicity')){?> selected <?php } ?>>
									<?php echo $key['label'] ?>
								</option>
								<?php }?>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</li>
		</ul>
	 </div>
	<?php } ?>
	
	<?php if ($customerGroupId == 2) { ?>
	<div class="fieldset">
		<h2 class="legend">
			<label class="required"><em>*</em><?php echo $this->__('Public Profile') ?></label>
			<div class="tooltip-outer">
				<span class="intergotive-sign">?</span>
				<div class="tooltip" style="display:none">Your account profile is visible to Artists with only, Your Name, Position, Company and Photo. *Your email, phone, address and other details are never revealed.</div>
			</div>
		</h2>
		<ul class="form-list">
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Position / Title" title="Position" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('position')) ?>" class="input-text required-entry" name="position" id="position" />
					</div>
				</div>
			</li>
			<li class="fields">
				<div class="field">
					<div class="input-box">
						<input type="text" placeholder="Company Name" title="Company Name" value="<?php echo $this->escapeHtml($this->getCustomer()->getData('company_name')) ?>" class="input-text required-entry" name="company_name" id="company_name" />
					</div>
				</div>
			</li>
			<li class="fields cstm-select-outer">
				<div class="field">
					<div class="input-box">
						<select name="industry_type" id="industry_type" class="input-text required-entry" >
							<option value="">Industry You work in (closest match)</option>
							<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('industry_type')->getSource()->getAllOptions();?>
							<?php foreach($options as $key): ?>
								<?php if(!empty($key["value"])) { ?>
								<option value="<?php echo $key['value'] ?>"<?php if($key['value']==$this->getCustomer()->getData('industry_type')){?> selected <?php } ?>>
									<?php echo $key['label'] ?>
								</option>
								<?php }?>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</li>
			<li class="fields">
				<div class="tooltip-outer tool-full">
					<span class="intergotive-sign" style="margin-left:0px">Read why setting your criteria correctly is important</span>
					<div class="tooltip" style="display:none">Selecting your Hiring frequency determines a big part of the score that Artists see when submitting. Selecting the correct Type of work you regularly use, adds points to the score and matches you with the kind of Artists you want to work with. *Please take your time and carefully add these categories.</div>
				</div>
			</li>
			<li class="fields">
				<div class="field illstrator-outer">
					<label for="hire_illustrators" class="required"><em>*</em><?php echo $this->__('I hire Illustrators') ?></label>
					<div class="input-box">
						<ul id="hire_illustration_frequency">
							<li>
								<input 	type="radio" class="hire_illustrators validate-one-required-by-name" name="hire_illustrators" value="Frequently" <?php echo ($this->getCustomer()->getData('hire_illustrators')=='Frequently')?'checked':'' ?>>
								<label>Frequently</label>
							</li>
							<li>
								<input  type="radio" class="hire_illustrators validate-one-required-by-name" name="hire_illustrators" value="Sometimes" <?php echo ($this->getCustomer()->getData('hire_illustrators')=='Sometimes')?'checked':'' ?>>
								<label>Sometimes</label>
							</li>
							<li>
								<input  type="radio" class="hire_illustrators validate-one-required-by-name" name="hire_illustrators" value="Never" <?php echo ($this->getCustomer()->getData('hire_illustrators')=='Never')?'checked':'' ?>>
								<label>Never</label>
							</li>
						</ul>
					</div>
				</div>
			</li>
            <?php if($this->getCustomer()->getData('hire_illustrators')=='Never' || empty($this->getCustomer()->getData('hire_illustrators'))){
    
                    $illustrationCategoryClass = "display-none";
                }
            ?>
			<li class="fields <?php echo $illustrationCategoryClass ?>" id="il38">
				<div class="field">
					<label for="work_type_use_for_illustration" class="type-of-work"><em></em><?php echo $this->__('The type of work I use for Illustration (Select 18):&nbsp;&nbsp;') ?></label><label class="how_many_selected_profile_page" id="label_hire_illustrators_selected"></label>
                    <div class="validation-advice" style="display:none" id="minill">Please select 18 Categories.</div>
					<div class="input-box">
						<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('work_type_use_for_illustration')->getSource()->getAllOptions();?>
						<ul class="custom-checkbox" id="ul-illustration-categories">
						<?php foreach ($options as $option):?>
							<?php if($option["value"] != "") { ?>
							<li><input type="checkbox" value="<?php echo $option['value'] ?>" name="work_type_use_for_illustration[]" <?php if (in_array($option['value'], explode(',', $this->getCustomer()->getData('work_type_use_for_illustration')))) echo "checked" ?> class="il_checked"><span class="chaked-mark"></span><?php echo $option['label'] ?></li>
							<?php } ?>
						<?php endforeach;?>	
						</ul>		
					</div>
				</div>
			</li>
            
			<li class="fields">
				<div class="field illstrator-outer">
					<label for="hire_photographers" class="required"><em>*</em><?php echo $this->__('I hire Photographers') ?></label>
					<div class="input-box">
						<ul id="hire_photography_frequency">
							<li>
								<input  type="radio" class="hire_photographers validate-one-required-by-name" name="hire_photographers" value="Frequently" <?php echo ($this->getCustomer()->getData('hire_photographers')=='Frequently')?'checked':'' ?>>
								<label>Frequently</label>
							</li>
							<li>							
								<input 	type="radio" class="hire_photographers validate-one-required-by-name" name="hire_photographers" value="Sometimes" <?php echo ($this->getCustomer()->getData('hire_photographers')=='Sometimes')?'checked':'' ?>>
								<label>Sometimes</label>
							</li>
							<li>
								<input  type="radio" class="hire_photographers validate-one-required-by-name" name="hire_photographers" value="Never" <?php echo ($this->getCustomer()->getData('hire_photographers')=='Never')?'checked':'' ?>>
								<label>Never</label>
							</li>
						</ul>
					</div>
				</div>
			</li>
            <?php if($this->getCustomer()->getData('hire_photographers')=='Never' || empty($this->getCustomer()->getData('hire_photographers'))){ 
                $photographyCategoryClass = "display-none";
            }
            ?>
			<li class="fields  <?php echo $photographyCategoryClass ?>" id="ph35">
				<div class="field">
					<label for="work_type_use_for_photography" class="required type-of-work"><em>*</em><?php echo $this->__('The type of work I use for Photography (Select 18):&nbsp;&nbsp;') ?></label><label class="how_many_selected_profile_page" id="label_hire_photography_selected"></label>
                    <div class="validation-advice" style="display:none" id="minpho">Please select 18 Categories.</div>
					<div class="input-box">
						<?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('work_type_use_for_photography')->getSource()->getAllOptions();?>
						<ul class="custom-checkbox"  id="ul-photography-categories">
						<?php foreach ($options as $option):?>
							<?php if($option["value"] != "") { ?>
							<li><input type="checkbox" value="<?php echo $option['value'] ?>" name="work_type_use_for_photography[]" <?php if (in_array($option['value'], explode(',', $this->getCustomer()->getData('work_type_use_for_photography')))) echo "checked" ?> class="ph_checked"><span class="chaked-mark"></span><?php echo $option['label'] ?></li>
							<?php } ?>
						<?php endforeach;?>	
						</ul>
					</div>
				</div>
			</li>
             
			<li class="fields">
				<div class="field illstrator-outer">
					<label for="looking_for_information" class="required"><em>*</em><?php echo $this->__('Information about what you’re looking for') ?></label>
					<div class="input-box">
						<textarea class="textarea required-entry" placeholder="e.g. Our publication works mainly with political figures rendered in a cartoon caricature style. From time to time we do use realism illustration for our covers." cols="15" rows="2" title="Information about what you’re looking for" name="looking_for_information" id="looking_for_information"><?php echo $this->getCustomer()->getData('looking_for_information'); ?></textarea>
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field illstrator-outer">
					<label for="not_want_to_see_information" class="required"><em>*</em><?php echo $this->__('Information about what you don’t want to see') ?></label>
					<div class="input-box">
						<textarea class="required-entry textarea" placeholder="e.g. Please do not submit portfolios with images of black velvet Elvis portraits or clowns." cols="15" rows="2" title="Information about what you’re looking for" name="not_want_to_see_information" id="not_want_to_see_information"><?php echo $this->getCustomer()->getData('not_want_to_see_information'); ?></textarea>
					</div>
				</div>
			</li>			
			<li class="fields">
				<div class="field illstrator-outer">
					<label for="follow_update" class="required"><em>*</em><?php echo $this->__('When I follow someone, I want to see Updates') ?></label>
					<div class="tooltip-outer">
						<span class="intergotive-sign">?</span>
						<div class="tooltip" style="display:none">When Art Directors Follow Artists, they receive one scheduled email notification (if the Artists Updated their Portfolio). *All the Artists you follow, and that have updated are aggregated into one email, with links to each Artist.</div>					
					</div>
					<div class="input-box">
					<ul>
						<li>
							<input  type="radio" class="validate-one-required-by-name" name="follow_update" value="Daily" <?php echo ($this->getCustomer()->getData('follow_update')=='Daily')?'checked':'' ?>>
							<label>Daily</label>
						</li>
						<li>						
							<input  type="radio" class="validate-one-required-by-name" name="follow_update" value="Weekly" <?php echo ($this->getCustomer()->getData('follow_update')=='Weekly')?'checked':'' ?>>
							<label>Weekly</label>
						</li>
						<li>
							<input  type="radio" class="validate-one-required-by-name" name="follow_update" value="Monthly" <?php echo ($this->getCustomer()->getData('follow_update')=='Monthly')?'checked':'' ?>>
							<label>Monthly</label>
						</li>
					</ul>
					</div>
				</div>
			</li>
		</ul>
	 </div>
	<?php } ?>
    
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button profile-submit"><span><span><?php echo $this->__('Save') ?></span></span></button>
		<!--<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>-->
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
<script type="text/javascript">
   $j = jQuery.noConflict();
   function readURL(input) {
       if (input.files && input.files[0]) {
           var reader = new FileReader();

           reader.onload = function(e) {

               $j('#preview2').attr('src', e.target.result);
           }

           reader.readAsDataURL(input.files[0]);
       }
   }
	var minillcount = 0;
	var minphocount = 0;
	var selected = [];
	
	window.onload = function (){
		jQuery('#ph35 input:checked').each(function() {
			selected.push(jQuery(this).attr('name'));
		});
		minphocount = selected.length;
		selected = [];
		jQuery('#il38 input:checked').each(function() {
			selected.push(jQuery(this).attr('name'));
		});		
		minillcount = selected.length;
		getState(jQuery("#country option:selected").attr('country_code'));
		
	}
	
	jQuery('body').on('change', '#work_type_use_for_illustration', function () {
		selected = []
		jQuery('#il38 input:checked').each(function() {
			selected.push(jQuery(this).attr('name'));
		});		
		minillcount = selected.length;
	});
	jQuery('body').on('change', '#work_type_use_for_photography', function () {
		selected = []
		jQuery('#ph35 input:checked').each(function() {
			selected.push(jQuery(this).attr('name'));
		});
		minphocount = selected.length;
	});

    //Used for Artist and Director
	jQuery('body').on('click', '.il_checked', function () {
		selected = []
		jQuery('#il38 input:checked').each(function() {
			selected.push(jQuery(this).attr('name'));
		});		
        
        //global var
        minillcount = selected.length
		
        var selecteditems = minillcount;
        var maxLimit = 18;
        var message;
        
        if(selecteditems < maxLimit){
            var leftItems = maxLimit - selecteditems;
            message = "Select " + leftItems + " more";
        }else if(selecteditems == maxLimit){
            message = "Selection Complete";
        }else if(selecteditems > maxLimit){
            message = "Selection Complete";
            jQuery(this).prop( "checked", false );
            alert("Selection Complete. If you wish to change, un-select already selected.");
        }
        
        jQuery("#minill").hide();
        jQuery("#label_hire_illustrators_selected").text(message);
	});
    
    //Used for Artist and Director
	jQuery('body').on('click', '.ph_checked', function (event) {
		selected = []
		jQuery('#ph35 input:checked').each(function() {
			selected.push(jQuery(this).attr('name'));
		});
		
        //global var
        minphocount = selected.length
		
        var selecteditems = minphocount;
        var maxLimit = 18;
        var message;
        
        if(selecteditems < maxLimit){
            var leftItems = maxLimit - selecteditems;
            message = "Select " + leftItems + " more";
        }else if(selecteditems == maxLimit){
            message = "Selection Complete";
        }else if(selecteditems > maxLimit){
            message = "Selection Complete";
            jQuery(this).prop( "checked", false );
            alert("Selection Complete. If you wish to change, un-select already selected.");
        }
        
		jQuery("#minpho").hide();
        jQuery("#label_hire_photography_selected").text(message);
        
	});
<?php if ($customerGroupId == 2) { ?>
	
	function minCheck(){
		jQuery("#minpho").hide();
		jQuery("#minill").hide();
		var pnever = [];
		var inever = [];
		var status = false;
		var focus = 0;
		jQuery('.hire_photographers').each(function() {
			if(jQuery(this).is(":checked"))
			pnever.push(jQuery(this).attr('value'));
		});	
		jQuery('.hire_illustrators').each(function() {
			if(jQuery(this).is(":checked"))
			inever.push(jQuery(this).attr('value'));
		});		
		if(inever[0] == "Never" && pnever[0] == "Never" ){
			jQuery("#minpho").hide();
			jQuery("#minill").hide();
			status = true;
		} 
		if (inever[0] != "Never" && minillcount < 18) {
			jQuery("#minill").show();
			focus = 1;
		}else {
			jQuery("#minill").hide();
			status = true;
		}

		if (pnever[0] != "Never" && minphocount < 18) {
			jQuery("#minpho").show();
			if(focus !=  1)
			focus = 2;	
		}else {
			jQuery("#minpho").hide();
			status = true;
		}
		if(focus == 1) {
			jQuery('#il38 input')[0].focus();
			status = false;
		}
		else if(focus == 2) {
			jQuery('#ph35 input')[0].focus();
			status = false;
		}
		return status;
	}
<?php } elseif ($customerGroupId == 1) { ?>	

	function minCheck(){
		jQuery("#minpho").hide();
		jQuery("#minill").hide();
		var status = false;
		var focus = 0;	
		if(jQuery('#il38').css('display') != 'none'  && minillcount < 18){
			focus = 1;
			jQuery("#minill").show();
		}else{
			jQuery("#minill").hide();			
			status = true;
		}
		if(jQuery('#ph35').css('display') != 'none'  != 0 && minphocount < 18){
			if(focus !=  1)
				focus = 2;
			jQuery("#minpho").show();
		}else{
			jQuery("#minpho").hide();		
			status = true;
		}
		if(focus == 1) {
			jQuery('#il38 input')[0].focus();
			status = false;
		}
		else if(focus == 2) {
			jQuery('#ph35 input')[0].focus();
			status = false;
		}
		return status;
	}

<?php } ?>
	jQuery('body').on('change', '#profession', function () {
		
		var value = jQuery(this).val();
		if(value == 35){
			 jQuery('#il38').hide();
			 jQuery('#work_type_use_for_illustration').removeClass('required-entry');
			 jQuery('#ph35').show();
			 jQuery('#work_type_use_for_photography').addClass('required-entry');
		}
		if(value == 38){
			 jQuery('#ph35').hide();
			 jQuery('#work_type_use_for_photography').removeClass('required-entry');
			 jQuery('#il38').show();
			 jQuery('#work_type_use_for_illustration').addClass('required-entry');
		}	
	});	
/* 	jQuery(".hire_photographers").on("change",function(){
		if(jQuery(this).val()=="Never"){
			jQuery("#work_type_use_for_photography").removeClass("required-entry");
			jQuery("#work_type_use_for_photography").removeClass("validation-failed");
			jQuery("#work_type_use_for_photography").next().hide();
		}else{
			jQuery("#work_type_use_for_photography").addClass("required-entry");
		}
	});
	jQuery(".hire_illustrators").on("change",function(){
		if(jQuery(this).val()=="Never"){
			jQuery("#work_type_use_for_illustration").removeClass("required-entry");
			jQuery("#work_type_use_for_illustration").removeClass("validation-failed");
			jQuery("#work_type_use_for_illustration").next().hide();
		}else{
			jQuery("#work_type_use_for_illustration").addClass("required-entry");
		}
	}); */
	jQuery('.intergotive-sign').on('mouseover',function(){
		jQuery(this).next('.tooltip').show();
	});
	jQuery('.intergotive-sign').on('mouseout',function(){
		jQuery(this).next('.tooltip').hide();
	});
	
    jQuery('body').on('change', '#hire_illustration_frequency li', function () {
        var hire_frequency = jQuery(this).text();
        hire_frequency = jQuery.trim(hire_frequency);
        if(hire_frequency.trim() == "Never"){
            jQuery("#il38").addClass("display-none");
        }else{
            jQuery("#il38").removeClass("display-none");
        }
        
    });
    
    jQuery('body').on('change', '#hire_photography_frequency li', function () {
        var hire_frequency = jQuery(this).text();
        hire_frequency = jQuery.trim(hire_frequency);
        if(hire_frequency.trim() == "Never"){
            jQuery("#ph35").addClass("display-none");
        }else{
            jQuery("#ph35").removeClass("display-none");
        }
        
    });
    
function validateYTVideo(event){
	if(jQuery('#youtube_link').val().trim() == ""){
		jQuery('#validation_link_yt_video').html('&nbsp;');
		jQuery('#is-yt-video-url-valid').val('true');
	}else{
			jQuery('#img-yt_video-url-loader').css('display','block');
			jQuery('#validation_link_yt_video').html('&nbsp;');
			jQuery('#is-yt-video-url-valid').val('false');
			jQuery('#save-profile-btn').attr("disabled",'disabled');
			var BaseUrl = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>";
			
			jQuery.ajax({
				url: BaseUrl + 'ajax/validateYoutubeVideo.php',
				type: 'post',
				data:{'youtubeVideoURL':jQuery('#youtube_link').val()},
				success: function(msg)
				{
					msg = jQuery.trim(msg);
					
					if(msg == 'error' || msg.indexOf("error") >= 0 || msg.indexOf("Error") >= 0 || msg.indexOf("ERROR") >= 0 || msg.toUpperCase().indexOf("SQL") >= 0){
							jQuery('#validation_link_yt_video').html('There seems to be a technical error. Please report the issue from contact us section under help.');
									
					}else{            
									if(msg.trim().length==0 && jQuery('#youtube_link').val().trim().length>0){
										jQuery('#validation_link_yt_video').css('color','green');
										jQuery('#validation_link_yt_video').html('Valid Youtube URL.');
										jQuery('#is-yt-video-url-valid').val('true');
										jQuery('#save-profile-btn').removeAttr("disabled");
									   
									}else{
										jQuery('#save-profile-btn').attr("disabled",'disabled');
										jQuery('#validation_link_yt_video').css('color','red');
										if(msg.trim() == 'Unauthorized'){
											jQuery('#validation_link_yt_video').html('This video does not have permissions to be embedded to other sites. Please contact Youtube video owner.');
										}else{
											jQuery('#validation_link_yt_video').html('Invalid Youtube URL e.g. URL https://youtu.be/C0DPdy98e4c');
										}
										
									}
									
											
								}

					jQuery('#img-yt_video-url-loader').css('display','none');
				},
				error: function (jqXHR, exception) {
						jQuery('#img-yt_video-url-loader').css('display','none');
						alert('There seems to be a technical error. Please report the issue from contact us section under help.');
				}
			});
	}
}


function getState(option) {
	var id = option;
	var BaseUrl = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>";
	jQuery.ajax({
		type: "get",
		url: BaseUrl + '/customer/account/ajaxCountryStates/',
		data: "country="+id,
		async: true,
		dataType: "json",
		success: function(data){
			jQuery('#append_state').html(data.html);
		}
	});		
}
</script>
