<?php
$customerData = Mage::getSingleton('customer/session')->getCustomer();
//echo '<pre>';
//print_r($customerData);
$customerId = $customerData->getId();
$customeremail=$customerData->getEmail();
?>

<div class="page-title"><h3>Help</h3></div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('artishelp')->toHtml(); ?> 
<h2 id="helpcontact" class="title">Contact Us</h2>
<div class="help-cntnt helpcontact-add">
<input type="hidden" name="email" class="email" value="<?php echo $customeremail;  ?>">
<input type="hidden" name="adminemail" class="adminemail" value="<?php echo Mage::getStoreConfig('trans_email/ident_support/email'); ?>">
<ul>
<li>Please select from the following ...</li>
<li><select id="state" name="state">
<option>I&rsquo;m Having Technical Issues</option>
<option>I Need to Make a Return</option>
<option>I Have a Suggestion</option>
<option>I Have an Other Issue</option>
</select></li>
<li><textarea name="briefdescription" class="descp" placeholder="Brief Description"></textarea></li>
<li>
<div class="buttons-set"><button class="button" id="sendmsg"  title="Save" type="submit"><span><span>send</span></span></button></div>
</li>
</ul>
</div>
</div>
</div>

<script type="text/javascript">
		jQuery(document).ready(function(){
		var BaseUrl = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>"; 
		
	jQuery("#sendmsg").click(function(){
		//alert("hello");
		//var id=jQuery(this).attr("id");
		var customeremail=jQuery(".email").val();
        var adminemail=jQuery(".adminemail").val();
		var ques=jQuery("#state option:selected").text();
        var msg=jQuery(".descp").val();
		//alert(msg);
		//alert(ques);
		if(msg==""){
			
			alert("Please enter Brief Description");
		}
		else{
		jQuery.ajax({
	  url: BaseUrl+'ajax/helpmsg.php',
	  type:        'post',
	  data:{'email':customeremail,'adminemail':adminemail,'ques':ques,'msg':msg},
	  success: function(msg)
	   {
		if (msg) {
		   alert("message send successfully");
		 // jQuery(".loader-img").hide();
		 //  window.location.reload(); 
		   
		} 
	   }
	});
		}
	});
								
	});
		
	</script>
