<?php
/**
 * @package   Revolution Slider
 * @author    ThemePunch <info@themepunch.com>
 * @link      http://revolution.themepunch.com/
 * @copyright 2017 ThemePunch
 */

$operations = new RevSliderOperations();
$arrValues = $operations->getGeneralSettingsValues();

$includes_globally = RevSliderBase::getVar($arrValues, 'includes_globally', 'on');
$pages_for_includes = RevSliderBase::getVar($arrValues, 'pages_for_includes', '');
$show_dev_export = RevSliderBase::getVar($arrValues, 'show_dev_export', 'off');
$change_font_loading = RevSliderBase::getVar($arrValues, 'change_font_loading', '');
$enable_logs = RevSliderBase::getVar($arrValues, 'enable_logs', 'off');
$load_all_javascript = RevSliderBase::getVar($arrValues, 'load_all_javascript', 'off');

$pack_page_creation = RevSliderBase::getVar($arrValues, 'pack_page_creation', 'on');
$single_page_creation = RevSliderBase::getVar($arrValues, 'single_page_creation', 'off');

$width = RevSliderBase::getVar($arrValues, 'width', 1240);
$width_notebook = RevSliderBase::getVar($arrValues, 'width_notebook', 1024);
$width_tablet = RevSliderBase::getVar($arrValues, 'width_tablet', 778);
$width_mobile = RevSliderBase::getVar($arrValues, 'width_mobile', 480);

$load_google_fonts = RevSliderBase::getVar($arrValues, 'load_google_fonts', 'off');

?>
<div class='wrap'>
	<div class="clear_both"></div>
	<div class="title_line" style="margin-bottom:10px">
		<?php
		$icon_general = '<div class="icon32" id="icon-options-general"></div>';
		echo Mage::helper('nwdrevslider/framework')->apply_filters( 'rev_icon_general_filter', $icon_general );
		?>
        <a class="button-primary revgreen button_save_general_settings float_right mtop_10 mleft_10"><?php echo $this->__('Save Settings'); ?></a>
	</div>

	<div class="clear_both"></div>

	<div id="rs-global-settings-dialog-wrap">
		<form name="form_general_settings" id="form_general_settings">
			<script type="text/javascript">
				g_settingsObj['form_general_settings'] = {};

                (function(jQuery) {
                    jQuery(document).ready(function () {
                        RevSliderSettings.createModernOnOff();

                        jQuery('.tp-moderncheckbox').each(function () {
                            RevSliderSettings.onoffStatus(jQuery(this));
                        });
                    });
                })($nwd_jQuery);
			</script>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Include RevSlider libraries globally:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input type="checkbox" id="includes_globally_1" name="includes_globally" class="tp-moderncheckbox" data-unchecked="off" <?php Mage::helper('nwdrevslider/framework')->checked($includes_globally, "on");?>>
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("ON - Add CSS and JS Files to all pages. </br>Off - CSS and JS Files will be only loaded on pages specified below and on pages with 'nwdrevslider_default' layout update handle added."); ?></i>
				</div>
			</div>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Pages to include RevSlider libraries:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input type="text" class="regular-text" id="pages_for_includes" name="pages_for_includes" value="<?php echo $pages_for_includes; ?>">
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Specify the handles or url keys for pages on the front end where slider includes will be included to. Example: cms_index_index,catalog_product_view,about-us"); ?></i>
				</div>
			</div>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Load all JavaScript libraries:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input type="checkbox" id="load_all_javascript_1" name="load_all_javascript" class="tp-moderncheckbox" data-unchecked="off" <?php Mage::helper('nwdrevslider/framework')->checked($load_all_javascript, 'on'); ?>>
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Enabling this will load all JavaScript libraries of Slider Revolution. Disabling this will let Slider Revolution load only the libraries needed for the current Sliders on page. Enabling this option can solve CDN issues."); ?></i>
				</div>
			</div>

            <div class="rs-global-setting">
                <div class="rs-gs-tc">
                    <label><?php echo $this->__("Enable Markup Export option:"); ?></label>
                </div>
                <div class="rs-gs-tc">
                    <input type="checkbox" id="show_dev_export_1" name="show_dev_export" class="tp-moderncheckbox" data-unchecked="off" <?php Mage::helper('nwdrevslider/framework')->checked($show_dev_export, 'on'); ?>>
                </div>
                <div class="rs-gs-tc">
                    <i style=""><?php echo $this->__("This will enable the option to export the Slider Markups to copy/paste it directly into websites."); ?></i>
                </div>
            </div>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Font Loading URL:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input id="change_font_loading" name="change_font_loading" type="text" class="regular-text" value="<?php echo $change_font_loading; ?>">
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Insert something in it and it will be used instead of https://fonts.googleapis.com/css?family= (For example: http://fonts.useso.com/css?family= which will also work for chinese visitors)"); ?></i>
				</div>
			</div>


			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Default Settings for Advanced Responsive Grid Sizes:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<div>
						<?php echo $this->__('Desktop Grid Width'); ?>
						<input id="width" name="width" type="text" class="textbox-small" value="<?php echo $width; ?>">
					</div>
					<div>
						<?php echo $this->__('Notebook Grid Width'); ?>
						<input id="width_notebook" name="width_notebook" type="text" class="textbox-small" value="<?php echo $width_notebook; ?>">
					</div>
					<div>
						<?php echo $this->__('Tablet Grid Width'); ?>
						<input name="width_tablet" type="text" class="textbox-small" value="<?php echo $width_tablet; ?>">
					</div>
					<div>
						<?php echo $this->__('Mobile Grid Width'); ?>
						<input name="width_mobile" type="text" class="textbox-small" value="<?php echo $width_mobile; ?>">
					</div>
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Define the default Grid Sizes for devices: Desktop, Tablet and Mobile"); ?></i>
				</div>
			</div>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Enable Logs:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input type="checkbox" id="enable_logs_1"name="enable_logs" class="tp-moderncheckbox" data-unchecked="off" <?php Mage::helper('nwdrevslider/framework')->checked($enable_logs, 'on'); ?>>
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Enable console logs for debugging."); ?></i>
				</div>
			</div>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Enable Blank Page Creation for Slider Packages:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input type="checkbox" id="" name="pack_page_creation" class="tp-moderncheckbox" data-unchecked="off" <?php Mage::helper('nwdrevslider/framework')->checked($pack_page_creation, 'on'); ?>>
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Enable option to automatically create a Blank Page if a Slider Pack is installed."); ?></i>
				</div>
			</div>

			<div class="rs-global-setting">
				<div class="rs-gs-tc">
					<label><?php echo $this->__("Enable Blank Page Creation for Single Sliders:"); ?></label>
				</div>
				<div class="rs-gs-tc">
					<input type="checkbox" id="" value="on" name="single_page_creation" class="tp-moderncheckbox" data-unchecked="off" <?php Mage::helper('nwdrevslider/framework')->checked($single_page_creation, 'on'); ?>>
				</div>
				<div class="rs-gs-tc">
					<i style=""><?php echo $this->__("Enable option to automatically create a Blank Page if a Single Slider is installed."); ?></i>
				</div>
			</div>

            <div class="rs-global-setting">
                <div class="rs-gs-tc">
                    <label><?php echo $this->__("Enable Google Font Download:"); ?></label>
                </div>
                <div class="rs-gs-tc">
                    <select id="load_google_fonts" name="load_google_fonts">
                        <option <?php Mage::helper('nwdrevslider/framework')->selected($load_google_fonts, 'off'); ?> value="off"><?php echo $this->__('Load from Google'); ?></option>
                        <option <?php Mage::helper('nwdrevslider/framework')->selected($load_google_fonts, 'preload'); ?> value="preload"><?php echo $this->__('Preload from Google'); ?></option>
                        <option <?php Mage::helper('nwdrevslider/framework')->selected($load_google_fonts, 'disable'); ?> value="disable"><?php echo $this->__('Disable, Load on your own'); ?></option>
                    </select>
                    <p><a id="trigger_font_deletion" class="button-primary revblue" original-title="" href="javascript:void(0);"><?php echo $this->__('Update Preload Fonts'); ?></a></p>
                </div>
                <div class="rs-gs-tc">
                    <i style=""><?php echo $this->__("Set this option on how to handle Google Fonts:"); ?></i>
                    <i style=""><?php echo $this->__("- Load from Google: will include fonts from Google Server."); ?></i>
                    <i style=""><?php echo $this->__("- Preload from Google: will download used fonts from Google Server and store them on your installation."); ?></i>
                    <i style=""><?php echo $this->__("- Disable: No fonts will be loaded, please include them yourself."); ?></i>
                </div>
            </div>

		</form>
	</div>
	<div style="margin: 10px 0;">
		<a class="button-primary revgreen button_save_general_settings" original-title=""><?php echo $this->__('Save Settings'); ?></a>
	</div>
	<span id="loader_general_settings" class="loader_round mleft_10" style="display: none;"></span>

</div>
