<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_Stripe
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 */

$_code = $this->getMethodCode();
$_addName = !$this->stripe->getSecurityMethod();

echo $this->getLayout()->createBlock('cryozonic_stripe/form_stripeJs')->toHtml();

?>

<?php if ($this->autoDetectCard()): ?>
<style type="text/css">
    <?php foreach ($this->getAcceptedCardTypes() as $code => $label): ?>
    input#cryozonic_stripe_cc_number.cctype-<?php echo $code; ?> { background-image: url(<?php echo $this->getSkinUrl("cryozonic_stripe/img/$code.png"); ?>); }
    <?php endforeach; ?>
</style>
<?php /* We are preloading the images so that there is no lag when they appear */ ?>
<div class="img-preload">
    <?php foreach ($this->getAcceptedCardTypes() as $code => $label): ?>
    <img src="<?php echo $this->getSkinUrl("cryozonic_stripe/img/$code.png"); ?>">
    <?php endforeach; ?>
</div>
<?php endif; ?>

<ul id="payment_form_<?php echo $_code ?>" style="display:none" class="admin stripe-new">
    <?php echo $this->getLayout()->createBlock('cryozonic_stripe/form_saved')->toHtml(); ?>
    <?php if ($this->showAcceptedCardTypes()): ?>
    <li class="stripe-new">
        <label for="<?php echo $_code ?>_cc_types"><?php echo $this->__('Accepted Card Types') ?></label>
        <div class="input-box" id="cryozonic-stripe-accepted-cards">
            <?php foreach ($this->getAcceptedCardTypes() as $code => $label): ?>
                <img src="<?php echo $this->getSkinUrl("cryozonic_stripe/img/$code.png"); ?>" alt="<?php echo $label; ?>" id="cryozonic_stripe_<?php echo $code; ?>_type" />
            <?php endforeach; ?>
        </div>
    </li>
    <?php endif; ?>

    <?php if ($this->stripe->isStripeElementsEnabled()): ?>

    <?php echo $this->getLayout()->createBlock('cryozonic_stripe/form_stripeElements')->toHtml(); ?>

    <?php else: ?>

    <li class="stripe-new">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry stripe-input input-text" id="<?php echo $_code ?>_cc_owner" <?php if ($_addName): ?>name="payment[cc_owner]" <?php endif; ?>value="<?php echo $this->getInfoData('cc_owner') ?>"/>
        </div>
    </li>
    <li class="stripe-new">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="<?php echo $_code ?>_cc_number" <?php if ($_addName): ?>name="payment[cc_number]" <?php endif; ?>title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="input-text required-entry stripe-input validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>" <?php echo $this->getOnKeyUpCardNumber(); ?> />
        </div>
    </li>
    <li class="stripe-new">
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_expiration" style="width:140px;" <?php if ($_addName): ?>name="payment[cc_exp_month]" <?php endif; ?>class="validate-cc-exp required-entry stripe-input">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" <?php if ($_addName): ?>name="payment[cc_exp_year]" <?php endif; ?>class="required-entry stripe-input">
            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
    <li class="stripe-new">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry stripe-input input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" <?php if ($_addName): ?>name="payment[cc_cid]" <?php endif; ?>style="width:3em;" value="<?php echo $this->getInfoData('cc_cid')?>" autocomplete="off" />
        </div>
    </li>
    <?php endif; ?>

    <?php endif; // isStripeElementsEnabled() ?>

    <li class="stripe-new" id="cryozonic-stripe-card-errors"></li>

    <?php if ($this->stripe->showSaveCardOption() || $this->stripe->alwaysSaveCard()): ?>
    <li class="stripe-new">
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_save">
                <?php if ($this->stripe->alwaysSaveCard()): ?>
                    <input type="hidden" class="input-hidden stripe-input" id="<?php echo $_code ?>_cc_save" name="payment[cc_save]" value="1"/>
                <?php else: ?>
                    <input type="checkbox" title="<?php echo $this->__('Save card for future purchases') ?>" class="input-checkbox stripe-input" id="<?php echo $_code ?>_cc_save" name="payment[cc_save]" checked="checked"/>
                    &nbsp;
                    <?php echo $this->__('Save card for future purchases') ?>
                <?php endif; ?>
            </label>
        </div>
    </li>
    <?php endif; ?>
</ul>

<script type="text/javascript">
    initSavedCards(true);
</script>
