<?php
/**
 * Create account form template
 * 
 * @category    design
 * @package     base_default
 * @author      Clarion Magento Team
 */
?>
<?php
$data=Mage::getSingleton('customer/session')->getCustomer();
$customerData = Mage::getSingleton('customer/session')->getCustomer();

$customerId = $customerData->getId();
$customer = Mage::getModel('customer/customer')->load($customerId);
$customerGroupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
 ?>
<?php
/**
 * edit account form template
 *
 * @var $this Mage_Customer_Block_form_edit
 */
?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="page-title">
    <h1><?php echo $this->__('Profile Settings') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
		<div class="outer-imgbox">
				<?php  $customer->getAvatar();  ?>
				<?php if($customer->getAvatar()==""){ ?>
				<span class="customer-img"><img src="<?php echo $this->getskinUrl() ?>images/nopropimg.png"/></span>
				<?php } else { ?>
			 <span class="customer-img"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);?>customer<?php  echo $customer->getAvatar();?>" height="125px"; width="125px" /></span>

				<?php } ?>
				<ul class="prof-img">
					<li>Upload a Square Image or it will be distorted <br/>200×200px at dpi Recommended</li>
					<li class="fields">
						<div class="input-box">
							<div class="img-choosefile-outer">
								<span class="img-choosefile">Choose File</span>
								<input type="file" name="avatar" title="<?php echo $this->__('Avatar') ?>" id="avatar" class="input-text" />
							</div>
						</div>
					</li>
				</ul>
		</div>
		<div class="make-chngs">Make Changes</div>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
			 
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
        <?php endif ?>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
	
	
			 
			 
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <!-- custom attributes -->
        <?php $attributeCollection = $this->helper('clarion_customerattribute/customerattribute')->getUserDefinedAttribures(); ?>
        <?php if($attributeCollection->count() > 0) : ?>
        
         <div class="fieldset" style="display:none;">
             <h2 class="legend"><?php echo $this->__('Additional Information') ?></h2>
             
             <!-- For all user defined attributes -->
             <?php foreach($attributeCollection as $attribute):?>
                <!-- For all user defined attributes which are set for customer edit account -->
                <?php if($this->helper('clarion_customerattribute/customerattribute')->isAttribureForCustomerAccountEdit($attribute->getAttributeCode())):?>
             
                    <?php $frontEndLabel = $attribute->getStoreLabel($this->helper('clarion_customerattribute/customerattribute')->getStoreId()); ?>
                    <?php $getAttributeCodeFunction = "get" .  str_replace(' ', '', ucwords(str_replace('_', ' ', $attribute->getAttributeCode()))); ?>
                    <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'required-entry' : '' ?>
                    <?php $fieldFrontendClass = ($attribute->getFrontendClass()) ? $attribute->getFrontendClass() : '' ?>
                    <?php $fieldValue = $this->escapeHtml($this->getCustomer()->$getAttributeCodeFunction()); ?>
                    <ul class="form-list">
                        <li class="fields">
                           <div class="field">
                               <label for="<?php echo $attribute->getAttributeCode(); ?>" <?php if($attribute->getIsRequired()):?>class="required"><em>*</em> <?php  else :?>><?php endif;?><?php echo $this->__($frontEndLabel) ?></label>
                               <div class="input-box">
                                   
                                   <?php if($attribute->getFrontendInput()== 'text'):?>
                                       <input type="text" name="<?php echo $attribute->getAttributeCode(); ?>" id="<?php echo $attribute->getAttributeCode(); ?>" value="<?php echo $fieldValue; ?>" title="<?php echo $this->__($frontEndLabel); ?>" class="input-text <?php echo $fieldRequiredClass; ?> <?php echo $fieldFrontendClass ;?>" />
                                       
                                   <?php elseif($attribute->getFrontendInput()== 'textarea'):?>
                                       <textarea class=" textarea <?php echo $fieldRequiredClass; ?> <?php echo $fieldFrontendClass ;?>" cols="15" rows="2" title="<?php echo $this->__($frontEndLabel); ?>" name="<?php echo $attribute->getAttributeCode(); ?>" id="<?php echo $attribute->getAttributeCode(); ?>"><?php echo $fieldValue; ?></textarea>
                                     
                                   <?php elseif($attribute->getFrontendInput()== 'date'):?>
                                    <input type="text" style="width:110px !important;" class=" input-text <?php echo $fieldRequiredClass; ?> " title="<?php echo $this->__($frontEndLabel); ?>" value="<?php echo $this->helper('clarion_customerattribute/customerattribute')->getFormattedDate($fieldValue); ?>" id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>">
                                    <img style="" title="Select Date" id="<?php echo $attribute->getAttributeCode(); ?>_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/clarion/customerattribute/grid-cal.gif') ?>">
                                        <script type="text/javascript">
                                        //&lt;![CDATA[
                                            Calendar.setup({
                                                inputField: "<?php echo $attribute->getAttributeCode(); ?>",
                                                ifFormat: "%m-%d-%Y",
                                                showsTime: false,
                                                button: "<?php echo $attribute->getAttributeCode(); ?>_trig",
                                                align: "Bl",
                                                singleClick : true
                                            });
                                        //]]&gt;
                                        </script>
                                     
                                    <?php elseif($attribute->getFrontendInput()== 'boolean'):?>
                                    <select id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>" title="<?php echo $this->__($frontEndLabel); ?>"<?php if ($attribute->getIsRequired()):?> class="validate-select required-entry "<?php endif; ?>>
                                        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute($attribute->getAttributeCode())->getSource()->getAllOptions();?>
                                        <?php foreach ($options as $option):?>
                                            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                                        <?php endforeach;?>
                                    </select>
                                        
                                    <?php elseif($attribute->getFrontendInput()== 'select'):?>
                                    <select id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>" title="<?php echo $this->__($frontEndLabel); ?>"<?php if ($attribute->getIsRequired()):?> class="validate-select required-entry "<?php endif; ?>>
                                        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute($attribute->getAttributeCode())->getSource()->getAllOptions();?>
                                        <?php foreach ($options as $option):?>
                                            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $fieldValue) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                                        <?php endforeach;?>
                                    </select>
                                        
                                    <?php elseif($attribute->getFrontendInput()== 'multiselect'):?>
                                    <select multiple="multiple" size="5" id="<?php echo $attribute->getAttributeCode(); ?>" name="<?php echo $attribute->getAttributeCode(); ?>[]" title="<?php echo $this->__($frontEndLabel); ?>"  class=" multiselect <?php if ($attribute->getIsRequired()):?> validate-select required-entry<?php endif; ?> ">
                                        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute($attribute->getAttributeCode())->getSource()->getAllOptions();?>
                                        <?php foreach ($options as $option):?>
                                            <option value="<?php echo $option['value'] ?>"<?php if (in_array($option['value'], explode(',', $fieldValue))) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
                                        <?php endforeach;?>
                                    </select>
                                        
                                   <?php endif;?>
                               </div>
                           </div>
                       </li>
                    </ul>
              <?php endif;?>
             <?php endforeach;?>
         </div>
    <?php endif; ?>
	
	<?php if($customerGroupId==3){  ?>
	<div class="set-up-paypal-outer">
		<div class="setup-titel">Set Up PayPal</div>
		<div class="set-email-outer">
			<label>Email used to receive payment</label>
			<div class="setup-email">
				<img src="<?php echo $this->getskinUrl ("images/paypal-icon.png") ?>" alt=""/>
				<p>Please set up your account on PayPal to receive payments. This is for deposits from Emergart to your PayPal account. </p>
				<p>Learn more at:<br/><a href="https://www.paypal.com/us/selfhelp/article/How-do-I-get-paid-FAQ1750">https://www.paypal.com/us/selfhelp/article/How-do-I-get-paid-FAQ1750</a></p>
				<div class="email-box">
					<input type="email" placeholder="Your PayPal Email" name="paypalemail" value="<?php echo $this->escapeHtml($this->getCustomer()->getPaypalemail()) ?>"/>
				</div>
				<p class="amnt-text">Test this by going to PayPal and sending yourself a small amount to make sure you are receiving funds.</p>
			</div>
		</div>
	</div>
			<ul class="misson-statement-outer">
				<li>
				<label for="description"><?php echo $this->__('Mission Statement') ?></label>
				<span> Please keep this brief-two or three short sentences. Character limit 250</span>
				<textarea name="artdescription"><?php echo $this->escapeHtml($this->getCustomer()->getArtdescription());?></textarea>
				</li>
					<li>
					<label for="description"><?php echo $this->__('Biography') ?></label>
					<span>Include your education or background,awards,shoes or any other information</span>
					<textarea name="biography"><?php echo $this->escapeHtml($this->getCustomer()->getBiography());?></textarea>
					</li>

			</ul>
			 <?php } ?>
    
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
	
	
	
</form>
<?php
$customerAddressId = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping();
if ($customerAddressId){
       $address = Mage::getModel('customer/address')->load($customerAddressId);
}
//echo "<pre>"; print_r($address);echo "</pre>";
$city=$address['city'];
$street=$address['street'];
$phone=$address['telephone'];
$zip=$address['postcode'];
$country=$address['country_id'];
$state=$address['region_id'];



?>

<form action="<?php echo $this->getUrl() ?>customer/account/customaddress/"  method="post" id="form-validate-new" enctype="multipart/form-data" autocomplete="off">
 <?php echo $this->getBlockHtml('formkey')?>
  <input type="hidden" name="customer_id" id="address_id" value="<?php echo $customerId;  ?>" />
  <input type="hidden" name="firstname" value="<?php echo $customer->getFirstname(); ?>"/>
   <input type="hidden" name="lastname" value="<?php echo $customer->getLastname(); ?>"/>   
   <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <ul class="form-list">
		 <li class="fields">
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('phone') ?></label>
                    <div class="input-box">
                        <input type="tel" name="telephone" value="<?php echo $phone; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                    </div>
                </div>
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="street" value="<?php echo $street; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
       
            <li class="fields">
                <div class="field">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" name="city" value="<?php echo $city; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </div>
               
            </li>
			
			<li class="fields">
			
			<?php
              $regions = Mage::getModel('directory/country')->load('US')->getRegions();
							//echo "<pre>"; print_r($regions);echo "</pre>";
			?>
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box" class="sel-state">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            <?php                        
                            
                            foreach($regions as $region)
                            {
                                echo "<option value='".$region->getCode()."'>".$region['name'] . "</option>";
                            }
                            ?>

                        </select>                       

                        </div>

			</li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?php echo $zip; ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                       
						
						<?php $_countries = Mage::getResourceModel('directory/country_collection')
									->loadData()
									->toOptionArray(false) ?>

	<select name="country_id" id="country">
		<option value="">-- Please Select --</option>
		<?php foreach($_countries as $_country): ?>
			<option value="<?php echo $_country['value'] ?>"<?php if($country==$_country['value']){?> selected <?php } ?>>
				<?php echo $_country['label'] ?>
			</option>
		<?php endforeach; ?>
	</select>

                    </div>
                </div>
            </li>
           
        <?php foreach ($primaryTypes as $code=>$type): ?>
            <li<?php if (!$address->isPrimary($type['address_type_id'])) echo ' class="control"' ?>>
            <?php if ($address->isPrimary($type['address_type_id'])): ?>
                <strong><?php echo $this->__("This is My Default %s Address", ucfirst($type['name'])) ?></strong>
            <?php else: ?>
                <input type="checkbox" id="primary_<?php echo $code ?>" name="primary_types[]" value="<?php echo $type['address_type_id'] ?>" class="checkbox" /><label for="primary_<?php echo $code ?>"><?php echo $this->__("Use as My Default %s Address", ucfirst($type['name'])) ?></label>
            <?php endif ?>
            </li>
        <?php endforeach ?>
        </ul>
		 </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getUrl('customer/address/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>

</form>

<?php if($customerGroupId==3){  ?>
<div class="questions">
<?php
 $tableName= Mage::getSingleton('core/resource')->getTableName('artist_qaadd');
 $answertable= Mage::getSingleton('core/resource')->getTableName('artist_qa');
$sqlPaymentSystem1="SELECT * FROM ".$tableName;
			try {
				$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem1);
				$result=$chkSystem->fetchall();
			}
			catch (Exception $e){
				 echo $e->getMessage();
			}
	?>
	<div class="qes-title"><?php echo count($result) ?> questions-profile page<a id="mckchange">Make Changes</a></div>
<form action="<?php echo Mage::getBaseUrl() ?>customer/account/artisqa" method="post" autocomplete="off"  enctype="multipart/form-data">
<?php $i=0; ?>
	<?php foreach($result as $res){ $i++; ?>
	
	<?php
	 $sqlPaymentSystem="SELECT * FROM ".$answertable." WHERE title='".$res['id']."' AND artistid='".$customerId."'";
			try {
				$chkSystem = Mage::getSingleton('core/resource')->getConnection('core_write')->query($sqlPaymentSystem);
				$resultnew=$chkSystem->fetchall();
			}
			catch (Exception $e){
				 echo $e->getMessage();
			}
			foreach($resultnew as $resd){
				$answer=$resd['answer'];
				
			}
			?>
		
	<input type="hidden" value="<?php echo $customerId;?>" name="customerid">
	
	<input type="hidden" name="question[]" value="<?php echo $res['id']; ?>"/>
	<input type="hidden" name="questext-<?php echo $i; ?>" value="<?php echo $res['question']; ?>">
	<div class="qes-box">
	<?php echo $res['question'];  ?>
	<?php
	if($answer!=""){
		$disabled="disabled";
		
	} ?>
	<textarea name="answer-<?php echo $i; ?>"  class="area" <?php echo $disabled; ?>><?php echo $answer; ?></textarea>
	</div>
    <?php } ?>
	<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>	
	</form>
</div>
<?php } ?>


<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>

<script type="text/javascript">
 // var customForm = new VarienForm('form-validate');
jQuery(document).ready(function(){
	
	jQuery("#mckchange").click(function(){
		
		jQuery(".area").removeAttr("disabled");
	});
	
	
	
});


</script>

<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('form-validate-new');
    //]]>
</script>
