<?php 
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner(); 
$helper= Mage::helper('marketplace');
if($isPartner==1){
	$filter = '';
	$filter_prostatus = '';
	$filter_data_frm = '';
	$filter_data_to = '';
	if(isset($_GET['s'])){
        $filter = $_GET['s'] != ""?$_GET['s']:"";
	}
	if(isset($_GET['prostatus'])){
        $filter_prostatus = $_GET['prostatus'] != ""?$_GET['prostatus']:"";
	}
	if(isset($_GET['from_date'])){
        $filter_data_frm = $_GET['from_date'] != ""?$_GET['from_date']:"";
	}
	if(isset($_GET['to_date'])){
        $filter_data_to = $_GET['to_date'] != ""?$_GET['to_date']:"";
	}
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$baseurl = Mage::getBaseUrl();
	$userId = $customer->getId();
	$subscription = Mage::getModel('customer/customer')->stripeApi($userId); // check user user subscription form stripe api
	$magentosubscription = Mage::getModel('customer/customer')->checkRecurring($userId); // check user user subscription from magento
	$disabled = $limiterror = "";
	$maxPortfolioImage = Mage::getStoreConfig('marketplace/marketplace_inventory/max_allowed_portfolio_product_images');
	if($subscription['code'] == 503) {
		if(count($this->getCollection()) >= $maxPortfolioImage){
			$disabled = "disabled";
		}
	} else {
		if(count($this->getCollection()) >= Mage::getStoreConfig('marketplace/marketplace_inventory/max_allowed_products')){
			$disabled = "disabled";
		}		
	}
	?>
	<script type="text/javascript">
	if (typeof jQuery == 'undefined'){
	    document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
	</script>
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<div class="page-title">
		<h1 style="float:left;"><?php echo $helper->__('My Portfolio') ?></h1>
		<div class="tooltip-outer">
			<span class="intergotive-sign">?</span>
			<div class="tooltip big-tooltip" style="display:none">
				<p>Click on “Add A New Portfolio Piece” When you finish uploading, the image will appear on this page.</p>
				<p>Select the images and order that will appear in your 12 Piece Portfolio. (Viewed by Art Directors when submitting) For Pro members, the maximum number of images in your Library is 500 - But only 12 will be used in Submissions.</p>
				<p>Art Directors who follow you will be notified whenever you update your portfolio. A portfolio is considered updated when:</p>
				<ol>
					<li>A new Portfolio Listing is created, and it is selected as one of the 12.</li>
					<li>When an Artist replaces the Image of an existing Selected Portfolio Piece.</li>
					<li>When an Artist deselect an image (Check Box) and then selects a different image.</li>
				</ol>
				<p>Note: Editing text, categories, descriptions or change in order are not considered updates.</p>
			</div>
		</div>		
	</div>
	<div class="account-message">
		<?php if($customer->getData('approval') == 65) { ?>
		<h2>Complete your <a href="<?php echo $baseurl."profile"; ?>">Profile</a> to Get Started.</h2>
		<?php } elseif($customer->getData('approval') == 64) { ?>
		<h2>We are currently reviewing your profile.</h2>
		<?php } else { ?>
			<?php if($magentosubscription['status'] == 2) { ?>
				<h2>Your plan is limited to 12 uploads. <a href="<?php echo $baseurl ?>membership/">Pro Members</a> get 500.</h2>
			<?php } elseif($magentosubscription['status'] == 3) { ?>
				<h2>Your Pro Membership is not active, images and submissions beyond your free 12 are hidden. <a href="<?php echo $baseurl."membership"; ?>">See Membership.</a></h2>
			<?php } ?>
		<?php } ?>
	</div>	
	<div class="wk_mp_design">
		<div class="fieldset wk_mp_fieldset width-100">
			<div class="grid">
				<div class="hor-scroll">
					<button class="button blue-big-button" title="Add a New Portfolio Piece" type="submit" id="blue-big-button" link="<?php echo $this->getUrl('Upload'); ?>" <?php if($customer->getData('approval') != 63) echo "disabled" ;?> <?php echo $disabled?>>
						<span><span><?php echo $helper->__('Add a New Portfolio Piece') ?></span></span>
					</button>
					<?php  if($limiterror != "") { ?>
					<div style="color: #ff6d34; padding-left: 2px; font-size: 13px;" id="max-pro-msg">
						You have reached your plan upload limit. You can remove an image and upload a new one, or change any existing images.
					</div>
					<?php } ?>
					<?php
					if($customer->getData('approval') == 63){	
						if(count($this->getCollection())==0){ ?>		
							<div class="fieldset wk_mp_fieldset">
								<div class="wk_emptymsg get-strd-con text-transform-inherit">
									<?php echo $helper->__("Get started by clicking the, ".'"Add a New Portfolio Piece"'." button above to add an image. When you're finished, the image icon will appear here and you will be able to edit or delete the image.") ?>
								</div>
							</div>
							<?php 
						} else{ ?>
							<form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/massdeletesellerpro') ?>" method="post" id="formmassdelete" name="formmassdelete">
								<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />							
								<table cellspacing="0" class="border wk_mp_list_table wk_mp_list_container_table">
									<thead>
										<tr class="wk_content">
											<th class="wk_first_td">
												<span class="label name">
													<?php echo $helper->__('Portfolio Pieces')?>
												</span>
												<div class="tooltip-outer">
													<span class="intergotive-sign">?</span>
													<div class="tooltip" style="display: none;">Up to 500 images (Pro Member) or up to 12 images (Free Account)</div>					
												</div>												
											</th>
											<th>
												<span class="label">
													<?php echo $helper->__('Action')?>
												</span>
												<div class="tooltip-outer">
													<span class="intergotive-sign">?</span>
													<div class="tooltip" style="display: none;">Select Edit to change images, text or description. Select Delete to permanently remove the image and all information.</div>					
                                                </div>
											</th>
											<th>
												<span class="label">
													<?php echo $helper->__('Selected Portfolio')?>(<span id="count_portfolio">0</span>/<span id="max_portfolio"><?= $maxPortfolioImage ?></span>)
												</span>
												<div class="tooltip-outer">
													<span class="intergotive-sign">?</span>
													<div class="tooltip t-loca" style="display: none;">Select a maximum of 12 images that Art Directors will see when you submit your portfolio. - If you already have 12 selected, you will need to deselect one of them in order to select another.</div>					
                                                </div>												
											</th>			    		
										</tr>
									</thead>
									<tbody>
										<?php 
										$i = 0;
										foreach($this->getCollection() as $products){
											$i++;
											$productMediaConfig = Mage::getModel('catalog/product_media_config');
											$salesdetail=Mage::getModel('marketplace/saleslist')->getSalesdetail($products->getEntityId());
											$_product=Mage::getModel('catalog/product')->load($products->getEntityId());
											?>
											<tr class="wk_row_view <?php echo $class = ($i == count($this->getCollection()))? 'wk_last_tr':''?>">
												<td class="wk_first_td">
													<input type="hidden" class="hidden_id" value="<?php echo $products->getEntityId(); ?>" />
													<div class="label name" title="<?php echo $products->getName(); ?>">
														<div class="wk_pro_divide1">
															<img src="<?php echo Mage::helper('catalog/image')->init($products, 'thumbnail')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300,120) ?>" class="image" />
														</div>
														<!--div class="wk_pro_divide2">
															<div style="width:100%;">
																<a href="<?php echo $_product->getProductUrl()?>" target="blank">
																	<?php echo $products->getName();?>
																</a>
															</div>
															<div style="width:100%;float:left;">
																<?php echo Mage::helper('core')->currency($products->getPrice(), true, false);?>
															</div>
														</div-->
													</div>
												</td>
												<td>
													<span class="label wk_action">
														<div data-type="<?php echo $products->getTypeId(); ?>" alt="<?php echo $helper->__('Edit')?>" title="<?php echo $helper->__('Edit')?>" class="mp_edit">Edit</div>
														<div alt="<?php echo $helper->__('Delete')?>" title="<?php echo $helper->__('Delete')?>" class="mp_delete">Delete</div>
													</span>	
												</td>
												<td <?php if($subscription['code'] == 503 and !$products->getData('is_portfolio')) { ?> class="td-hid-img" <?php } ?>>
													<?php if($subscription['code'] == 503) { ?><div class="hidden-image" id="hidden_image_<?= $products->getId() ?>" <?php if($products->getData('is_portfolio')) { ?> style="display:none" <?php } ?>><span class="desktop-hid">Hidden
		<div class="tooltip-outer tooltip-outer-i">
			<span class="intergotive-sign" style="color: black;padding: 4px 7px 2px 7px;">? </span>
			<div class="tooltip big-tooltip" style="display:none; right: -140px; top: 37px;width: 390px;">
				<p>To unhide this image, either purchase subscription or add it in your free <?= $maxPortfolioImage ?> piece portfolio using checkbox below.</p>
			</div>
		</div>	
                                                    </span><span class="mob-hid">Hidden</span></div><?php } ?>
													<span class="label wk_select_porfolio">
														<input type="checkbox" id="product_id_<?= $products->getId() ?>" class="portfolio-image-check is_portfolio" product_id="<?= $products->getId() ?>" <?php if($products->getData('is_portfolio')) { ?> checked <?php } ?>><span class="chaked-mark"></span>
													</span>	
												</td>			    		
											</tr>
											<?php
										}?>
									</tbody>
								</table>
							</form>
							<?php } ?>
					<?php } ?>
				</div>
			</div>
			<?php echo $this->getPagerHtml(); ?>		
		</div>	
		<div class="buttons-set">

		</div>
	</div>
	<div id="loader" class="cus-loader" style="display:none;">
		<div class="over-lay"></div>
		<div class="loader-body">
			<img id="loading-image" src="">
		</div>
	</div>	
	<script>
	window.onload = function(){
		
		if( !jQuery.trim( jQuery('.account-message').html() ).length) {
			jQuery('.account-message').hide();
		}
		jQuery('.tooltip-outer').prev('h1').css('display','inline-block'); // tooltip in same line
		
		jQuery.ajax({
			type: "get",
			url: "<?php echo Mage::getBaseUrl(); ?>customer/account/ajaxPortfolioImage/",
			data: "imgcount=1",
			async: true,
			dataType: "json",
			success: function(data){
				jQuery("#count_portfolio").html(data.imgcount);
			}
		});		
		
	}	
	var $wk_jq=jQuery.noConflict();
	var newCustomerProductForm1 = new VarienForm('formmassdelete', true);
	(function($wk_jq){
		$wk_jq( "#special_from_date" ).datepicker({dateFormat: "yy-mm-dd"});
		$wk_jq( "#special_to_date" ).datepicker({dateFormat: "yy-mm-dd"});
		$wk_jq('body').delegate('.mp_edit','click',function(){
			var id=$wk_jq(this).parents('.wk_row_view').find('.hidden_id').val();	
			
				var $type_id=$wk_jq(this).attr('data-type');	
				if($type_id=='simple')
					window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedsimple/') ?>".concat("id/",id);	
				if($type_id=='downloadable')
					window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapproveddownloadable/') ?>".concat("id/",id);			
				if($type_id=='virtual')
					window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedvirtual/') ?>".concat("id/",id);		
				if($type_id=='configurable')
					window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/editapprovedconfigurable/') ?>".concat("id/",id);
					<?php
					 echo $this->getChildHtml('mpgrouped_productslist');
					echo $this->getChildHtml('mpbundle_productslist');
					?>
			
		});
		$wk_jq('#mass_delete_butn').click(function(e){
			var flag =0;
			$wk_jq('.mpcheckbox').each(function(){
				if (this.checked == true){
					flag =1;
				}
			});
			if (flag == 0){
				alert("<?php echo $helper->__(' No Checkbox is checked ') ?>");
				return false;
			}
			else{
				var dicisionapp=confirm('<?php echo $helper->__(" Are you sure you want to delete these product ? ")?>');
				if(dicisionapp==true){
					$wk_jq('#form-customer-product-new').submit();
				}else{
					return false;
				}
			}
		});

	    $wk_jq('#mpselecctall').click(function(event) {
	        if(this.checked) {
	            $wk_jq('.mpcheckbox').each(function() {
	                this.checked = true;      
	            });
	        }else{
	            $wk_jq('.mpcheckbox').each(function() {
	                this.checked = false;           
	            });         
	        }
	    });

		$wk_jq('.mp_delete').click(function(){
			var id=$wk_jq(this).parents('.wk_row_view').find('.hidden_id').val();
			var dicisionapp=confirm('<?php echo $helper->__(" Are you sure you want to delete this product ? ")?>');
			if(dicisionapp==true)
				window.location = "<?php echo $this->getUrl('marketplace/marketplaceaccount/delete/') ?>".concat("id/",id);
		});
	})($wk_jq);

	jQuery('#blue-big-button').on("click",function(){
		var url = jQuery(this).attr("link");
		window.location = url;
	})
	
	jQuery(document.body).on('mouseover','.intergotive-sign',function(){
		jQuery(this).next('.tooltip').show();
	});
	jQuery(document.body).on('mouseout','.intergotive-sign',function(){
		jQuery(this).next('.tooltip').hide();
	});
	
    //check portfolio image details
	jQuery('body').on('click', '.is_portfolio', function () {
		var product_id = jQuery(this).attr('product_id');
		jQuery('#loader').show();
		jQuery.ajax({
			type: "get",
			url: "<?php echo Mage::getBaseUrl(); ?>customer/account/ajaxPortfolioImage/",
			data: "product_id="+product_id,
			async: true,
			dataType: "json",
			success: function(data){
				if(data.status == false) {
					jQuery("#product_id_"+product_id).prop( "checked", false);
					<?php if($subscription['code'] == 503) { ?>
					jQuery("#hidden_image_"+product_id).show();
					jQuery("#hidden_image_"+product_id).parent('td').addClass('td-hid-img');
					<?php } ?>
					alert(data.code);
				}
				if(data.status == true) {
					jQuery("#count_portfolio").html(data.imgcount);
					<?php if($subscription['code'] == 503) { ?>
					if(jQuery("#product_id_"+product_id).prop( "checked")) {
						jQuery("#hidden_image_"+product_id).hide();
						jQuery("#hidden_image_"+product_id).parent('td').removeClass('td-hid-img');
					} else {
						jQuery("#hidden_image_"+product_id).show();
						jQuery("#hidden_image_"+product_id).parent('td').addClass('td-hid-img');
					}
					<?php } ?>
				}
				jQuery('#loader').hide();
			}
		});
		
	});
	</script>
	<?php 
}else{?>
	<h2 class="wk_mp_error_msg">
		<?php echo $helper->__("To Become Seller Please Contact Admin"); ?>
	</h2>
	<?php
} ?>