<?php 
$helper=Mage::helper('marketplace');
$product = Mage::getResourceModel('catalog/product');
$customer=Mage::getSingleton('customer/session')->getCustomer();
$customerid=Mage::getSingleton('customer/session')->getCustomerId();
$isPartner= Mage::getModel('marketplace/userprofile')->isPartner();
$allproduct = Mage::getResourceModel('catalog/product_collection');
$prductcount = count($allproduct) +1;
$product_hint_status = Mage::helper('marketplace')->getProductHintStatus();
if($isPartner==1){ ?>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<form action="<?php echo $this->getUrl('marketplace/marketplaceaccount/simpleproduct') ?>" enctype="multipart/form-data" method="post" id="form-customer-product-new">
		<div class="page-title">
			<h1 style="float:left;"><?php echo $helper->__('Portfolio Piece') ?></h1>
		</div>		
		<div class="wk_mp_design">
			<div class="block block-account">	
				<div class="block-title">	
					<strong><span><h4><?php echo $helper->__('Single Portfolio Piece') ?></h4></span></strong>
				</div>
			</div>
			<div class="fieldset wk_mp_fieldset">
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
				<input type="hidden" name="attribute_set_id" id="attribute_set_id" value="<?php echo $this->getRequest()->getParam('set')!=''? $this->getRequest()->getParam('set'):4;  ?>" />
				<input type="hidden" name="type_id" id="producttype" value="<?php echo $this->getRequest()->getParam('type')?>" />
				<input type="hidden"  name="wstoreids" id="wstoreids" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" title="wstoreids" class="" />
				<?php if($customer->getProfession() == 38 ) { ?>
				<input type="hidden"  name="category[]" value="3"/>
				<?php } elseif($customer->getProfession() == 35 ) {?>
				<input type="hidden"  name="category[]" value="4"/>
				<?php } ?>
				<input type="hidden"  name="description" value="Folyoz product description"/>
				<input type="hidden"  name="short_description" value="Folyoz product short description"/>
				<input type="hidden"  name="sku" value="<?php echo 'folyz_sku_'.$prductcount; ?>"/>
				<input type="hidden"  name="price" value="0"/>
				<input type="hidden"  name="stock" value="1"/>
				<input type="hidden"  name="is_in_stock" value="1"/>
				<ul class="form-list" id="wk_bodymain">
					<li id="image-li">
						<label class="required" style="margin-bottom: 0.8em;">Image size: 2MB max. Extensions: .jpeg .jpg .png only. Cannot have a dot (.) within the file name.</label>
						<?php if($product_hint_status && Mage::helper('marketplace')->getProductImageHint()){?>
						<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::helper('marketplace')->getProductImageHint() ?>"/>
						<?php } ?>
						<div class="out-custom-img">
							<div id="otherimages">
								<div id='childDiv1'>
									<div height="264px" width="264px" max-height="264px" style="border: 1px solid silver;margin-bottom:20px; ">
										<div style="width: 100%;height: 264px;line-height: 264px; text-align:center">Upload an Image
											<img id="preview1" class='removeAltBorder' style="vertical-align: middle;display: inline-block;border:0" ></img>
										</div>
									</div>
									<div class="otimg">
										<div class="img-choosefile" style="width: auto;margin-right: 20px;background: none;position: relative;top: -5px;">
										<label for="rad1" style="cursor: pointer;width: auto;">Upload Image</label>
										<input type="file" accept=".png,.jpg,.jpeg" id="rad1"  name="images[]" class='wk_imagevalidate'  style="display: none"/></div>
										<div class="rmvimg"><a href="javascript:void(0)" onclick="removeUrl1(this);"><?php echo $helper->__('Delete Image'); ?></a></div>
									</div>
									<div class="mchoose">
										<input type="radio" value='' id="dim1" class='defaultimage margin-top-0-percent' name="defaultimage">
										<span class='defaultimageset'><?php echo $helper->__("Use as Main Image"); ?></span>
									</div>
								</div>
							</div>
						</div>
					</li>					
					<li>
						<label class="required"><em>*</em><?php echo $helper->__('Enter a title') ?>:</label>
						<div class="input-box">
							<input type="text" class="required-entry input-text" name="name" id="name" />
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="style" class="required"><em>*</em><?php echo $this->__('Select up to 10 Style / Medium categories. (Used in Search)') ?>:</label>
							<div class="input-box">
								<select multiple="multiple" size="5" id="style" name="style[]" title=""  class="required-entry multiselect multipleSelect">
									<?php $options = $product->getAttribute('style')->getSource()->getAllOptions();?>
									<?php foreach ($options as $option):?>
										<?php if($option["value"] != "") { ?>
										<option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
										<?php } ?>
									<?php endforeach;?>
								</select>
							</div>
						</div>
					</li>					
					<li>
						<label class="required"><em>*</em><?php echo $helper->__('Width') ?>:</label>
						<div class="input-box">
							<input type="text" class="required-entry input-text" name="width" id="width" />
						</div>
					</li>
					<li>
						<label class="required"><em>*</em><?php echo $helper->__('Height') ?>:</label>
						<div class="input-box">
							<input type="text" class="required-entry input-text" name="height" id="height" />
						</div>
					</li>
					<li>
						<div class="input-box">
							<input type="radio" class="" name="inch_cm" id="inch_cm" value="51"/> inches 
							<input type="radio" class="" name="inch_cm" id="inch_cm" value="50"/> cm
						</div>
					</li>
					<li>
						<label class="required"><em>*</em><?php echo $helper->__('Enter a Client (Enter Promotional if no client)') ?>:</label>
						<div class="input-box">
							<input type="text" class="required-entry input-text" name="client" id="client" />
						</div>
					</li>
					<li>
						<div class="input-box">
							<label class="required"><em>*</em><?php echo $helper->__('Is this image available for Re-Licensing?') ?>:</label>
							<input type="radio" class="" name="re_licensing" id="re_licensing" value="1"/> Yes 
							<input type="radio" class="" name="re_licensing" id="re_licensing" value="0"/> No
						</div>
					</li>
					<li>
						<label class="required"><em>*</em><?php echo $helper->__('Description of the project.') ?>:</label>
						<div class="input-box">
							<textarea class="textarea required-entry" placeholder="e.g. This image was used as a magazine cover illustrating how fun it is to fly a kite" cols="15" rows="2" title="Information about what you’re looking for" name="project_desc" id="project_desc"></textarea>					
						</div>
					</li>
					<li>
						<label class="required"><em>*</em><?php echo $helper->__('Keywords for search, e.g., red, kite, sky, clouds, fun, whimsical, cartoon, etc. Separated with commas.') ?>:</label>
						<div class="input-box">
							<textarea class="textarea required-entry" placeholder="e.g., red, kite, sky, clouds, fun, whimsical, cartoon" cols="15" rows="2" title="Information about what you’re looking for" name="search_keyword" id="search_keyword"></textarea>					
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="categories" class="required"><em>*</em><?php echo $this->__('Select up to 20 descriptive (Genre) categories. Be very specific and relative to this image. (Used in Search)') ?>:</label>
							<div class="input-box">
								<select multiple="multiple" size="5" id="categories" name="categories[]" title=""  class="required-entry multiselect multipleSelect">
									<?php $options = $product->getAttribute('categories')->getSource()->getAllOptions();?>
									<?php foreach ($options as $option):?>
										<?php if($option["value"] != "") { ?>
										<option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option>
										<?php } ?>
									<?php endforeach;?>
								</select>
							</div>
						</div>
					</li>
					<li style="display:none;">
						<label class="required"><em>*</em><?php echo $helper->__('Tax Class') ?>:</label>
						<?php
						if($product_hint_status && Mage::helper('marketplace')->getProductTaxHint()){?>
							<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::helper('marketplace')->getProductTaxHint() ?>"/>
						<?php
						} ?>
						<div class="input-box">
							<select id="tax_class_id" class=" required-entry required-entry select" name="tax_class_id">
								<option value=""><?php echo $helper->__('Please Select')?></option>
								<option value="0"><?php echo $helper->__('None')?></option>
								<?php
								$taxes=Mage::getModel('tax/class')->getCollection()
											->addFieldToFilter('class_type',array('eq'=>'PRODUCT'));
								foreach($taxes as $tax){
									?>
									<option value="<?php echo $tax->getId() ?>"><?php echo $tax->getClassName()?></option>
								<?php 
								} ?>
							</select>
						</div>
					</li>
					<li style="display:none;">
						<label class="required"><em>*</em><?php echo $helper->__('Weight') ?>:</label>
						<?php
						if($product_hint_status && Mage::helper('marketplace')->getProductWeightHint()){?>
							<img src="<?php echo $this->getSkinUrl('marketplace/images/quest.png'); ?>" class='questimg' title="<?php echo Mage::helper('marketplace')->getProductWeightHint() ?>"/>
						<?php
						} ?>
						<div class="input-box">
							<input type="text" class="required-entry validate-number validate-zero-or-greater validate-number-range number-range-0-99999999.9999 input-text" name="weight" id="weight" value="1"/>
						</div>
					</li>
					<?php echo $this->getChildHtml(); ?>
				</ul>
			</div>
		</div>
		<div class="simple-save">
			<button type="reset" class="button wk_mp_btn">
				<span><span><?php echo $helper->__('Reset') ?></span></span>
			</button>
			<button class="button wk_mp_btn" title="<?php echo $helper->__('Save') ?>" type="submit" id="save_butn">
				<span><span><?php echo $helper->__('Save') ?></span></span>
			</button>
		</div>
	</form>
	<script id="imageTemplate" type="text/x-jquery-tmpl">
		<div id='childDiv${index}'>
			<input type='file' name='images[]' class='wk_imagevalidate'/>
			<input type='radio'  onClick='defaultimagevalue(this)'  value=''  class='defaultimage' name='defaultimage'>
			<span class='defaultimageset'>
				<?php echo $helper->__('Base image'); ?>
			</span>
			<a href="javascript:void(0)" onclick="removeEvent('childDiv${index}')"><?php echo $helper->__('Remove'); ?></a>
		</div>
	</script>
	<div class="buttons-set">
		<p class="required">* <?php echo $helper->__('Required Fields') ?></p>		
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo $helper->__('Back') ?></a>
		</p>
	</div>	
	<?php
	$allowed_images = $helper->getAllowedImageExtension();
	?>	
	<script type="text/javascript">
	if (typeof jQuery == 'undefined'){
	    document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
	</script>
	<script src="<?php echo $this->getSkinUrl('marketplace/js/jquery.tmpl.min.js') ?>" type="text/javascript"></script>
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'tiny_mce/tiny_mce.js' ?>"></script>
	<script type="text/javascript">
	window.onload=function()
	{
	   	tinyMCE.init({
		    mode : "exact",
		    elements: "description_,descriptions_",
		    theme : "advanced",
		    plugins : "inlinepopups,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
		    theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
		    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
		    theme_advanced_toolbar_location : "top",
		    theme_advanced_toolbar_align : "left",
		    theme_advanced_path_location : "bottom",
		    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
		    theme_advanced_resize_horizontal : 'true',
		    theme_advanced_resizing : 'true',
		    apply_source_formatting : 'true',
		    convert_urls : 'false',
		    force_br_newlines : 'true',
		    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
		});
	};
	</script>
	<script> 
	var $wk_jq=jQuery.noConflict();	

	var newCustomerProductForm = new VarienForm('form-customer-product-new', true);

	$wk_jq( "#special_from_date").datepicker({'dateFormat':'yy:mm:dd'});
	$wk_jq( "#special_to_date" ).datepicker({'dateFormat':'yy:mm:dd'});

	var i=2;

	function showOtherImage(){
		$wk_jq("#imageTemplate").tmpl([{'index':i}]).appendTo("#otherimages");
		i++;
	}
	function removeEvent(divNum){
		var d = document.getElementById('otherimages');
		var olddiv = document.getElementById(divNum);
		d.removeChild(olddiv);
		i--;
	}
	function defaultimagevalue(object){
		var strs=$wk_jq(object).prev('input').val().split('\\'); 
	    $wk_jq(object).val(strs[strs.length-1]);
	}
	(function($wk_jq){

		$wk_jq('#save_butn').click(function(e){
			if(newCustomerProductForm.validator.validate()!=false){				     
				$wk_jq('#save_butn span span').text('<?php echo $helper->__("Saving")?>..');
				$wk_jq('.button').css('opacity','0.7');
				$wk_jq('.button').css('cursor','default');
				$wk_jq('.button').attr('disabled','disabled');
				$wk_jq('#form-customer-product-new').submit();
			}
		});
		
		$wk_jq('.input-text').change(function(){
			var validt = $wk_jq(this).val();
			var regex = /(<([^>]+)>)/ig;
			var mainvald = validt .replace(regex, "");
			$wk_jq(this).val(mainvald);	
	    });

	    $wk_jq("body").delegate('.wk_imagevalidate',"change",function(){
			$wk_jq( ".defaultimage" ).prop( "checked",false);
			var ext = $wk_jq(this).val().split('.').pop().toLowerCase();
			if($wk_jq.inArray(ext, [<?php echo $allowed_images ?>]) == -1) {
				$wk_jq(this).val('');
				alert('<?php echo $helper->__("Invalid extension! Please Upload an image")?>');
			}
		});

		$wk_jq('input#sku').change(function(){
			var len=$wk_jq('input#sku').val();
			var len2=len.length;
			if(len2==0){
				alert('<?php echo $helper->__("SKU can\'t be left empty")?>');
				$wk_jq('div#skuavail').css('display','none');
				$wk_jq('div#skunotavail').css('display','none');
			}
			else{
				$wk_jq.ajax({
					url: "<?php echo Mage::getUrl('marketplace/marketplaceaccount/verifysku');?>",
					type: "POST",
					data: {sku:$wk_jq('input#sku').val()},
					dataType: 'html',
					success:function($data){
						$data=JSON.parse($data);
						if($data.avl==1){
							$wk_jq('div#skuavail').css('display','block');
							$wk_jq('div#skunotavail').css('display','none');
						}
						else{
							$wk_jq('div#skunotavail').css('display','block');
							$wk_jq('div#skuavail').css('display','none');
							$wk_jq("input#sku").attr('value','');
						}
					}
				});
			}
		});

		$wk_jq("#wk_bodymain").delegate('.wk_plus ,.wk_plusend,.wk_minus, .wk_minusend ',"click",function(){
			var thisthis=$wk_jq(this);	
			if(thisthis.hasClass("wk_plus") || thisthis.hasClass("wk_plusend")){
				if(thisthis.hasClass("wk_plus"))
					thisthis.removeClass('wk_plus').addClass('wk_plus_click');
				if(thisthis.hasClass("wk_plusend"))
					thisthis.removeClass('wk_plusend').addClass('wk_plusend_click');
				thisthis.prepend("<span class='wk_node_loader'></span>");
				$wk_jq.ajax({
					url  	:   "<?php echo $this->getUrl('marketplace/marketplaceaccount/categorytree/');?>",
					type 	:   "POST",
					data 	:   {CID:thisthis.siblings("input").val(),
								ML:thisthis.parent(".wk_cat_container").css("margin-left").replace("px","")},
					dataType:   "html",
					success :   function(content){
						var newdata=  $wk_jq.parseJSON(content);
						len= newdata.length;
						var pxl= parseInt(thisthis.parent(".wk_cat_container").css("margin-left").replace("px",""))+20;
						thisthis.find(".wk_node_loader").remove();
						if(thisthis.attr("class") == "wk_plus")
						thisthis.attr("class","wk_minus");
						if(thisthis.attr("class") == "wk_plusend")
							thisthis.attr("class","wk_minusend");
						if(thisthis.attr("class") == "wk_plus_click")
							thisthis.attr("class","wk_minus");
						if(thisthis.attr("class") == "wk_plusend_click")
							thisthis.attr("class","wk_minusend");
					    for(i=0;i<len; i++){     
							id=newdata[i].id;
							nam=newdata[i].name;
							if(newdata[i].counting ==0){
								thisthis.parent(".wk_cat_container").after('<div class="wk_removable wk_cat_container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk_no"></span><span class="wk_foldersign"></span><span class="wk_elements wk_cat_name">'+ nam +'</span><input class="wk_elements" type="checkbox" name="category[]" value='+ id +'></div>');
							}else{
								thisthis.parent(".wk_cat_container").after('<div class="wk_removable wk_cat_container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk_plusend"></span><span class="wk_foldersign"></span><span class="wk_elements wk_cat_name">'+ nam +'</span><input class="wk_elements" type="checkbox" name="category[]" value='+ id +'></div>');   
							}
						}
						thisthis.parent(".wk_cat_container").nextAll().slideDown(300);
					}
				});			
			}
			if(thisthis.hasClass("wk_minus") || thisthis.hasClass("wk_minusend")){
				if(thisthis.attr("class") == "wk_minus")
					thisthis.attr("class","wk_plus");
				if(thisthis.attr("class") == "wk_minusend")
					thisthis.attr("class","wk_plusend");
				var thiscategory = thisthis.parent(".wk_cat_container");
				var marg= parseInt(thiscategory.css("margin-left").replace("px",""));
				while(thiscategory.next().hasClass("wk_removable")){
				  
				if(parseInt(thiscategory.next().css("margin-left").replace("px",""))>marg)
					thiscategory.next().slideUp("slow",function(){$wk_jq(this).remove();});
					thiscategory = thiscategory.next();	
					if(typeof thiscategory.next().css("margin-left")!= "undefined"){
						if( marg==thiscategory.next().css("margin-left").replace("px",""))
						{
						  break;
						}
					}
				}
			}		
		});
	})($wk_jq);
	</script>
<?php 
}else{ ?>
	<h2 class="wk_mp_error_msg">
		<?php echo $helper->__("To Become Seller Please Contact to Admin."); ?>
	</h2>
	<?php
} ?>
<script>
//upload
	$j(document).ready(function () {

		function isFileValid(fileName, fileSize){
			var isFileValid = true;
			var numberOfDotsInFilename = fileName.split('.').length - 1;

			if(numberOfDotsInFilename > 1 ){
				isFileValid = false;
				alert('File name cannot have Dot (.) within the name, please rename your file and upload');
			}
			//size in KB
			fileSize = fileSize*1;
			if(fileSize > 2048){
				isFileValid = false;
				alert('File size must be less than 2MB. Please optimize your file - See Help/ Image Sizes');
			}

			return isFileValid;
		}
		resizeImageFn = function(id){
						$j(id).css('visibility','hidden');
						setTimeout(function(){
							$j(id).removeAttr('style');
							$j(id).css({'vertical-align':'middle','display':'inline-block','margin-bottom':0,'border':0});
							if($j(id).height() > 264){
								$j(id).css({'display':'block','max-height':264,'margin':'auto'});
								$j(id).width('auto');
							}else if($j(id).width() > 264){
								$j(id).css('max-width',264);
								$j(id).height('auto');
							}
							$j(id).css('visibility','visible');
						},100);
		}
		$j('#rad1').on('change', function() {
				if (this.files && this.files[0]) {
					var fileSize = parseFloat(this.files[0].size / 1024).toFixed(2);
					if(isFileValid(this.value, fileSize)){
						var reader = new FileReader();
						reader.onload = function(e) {
							$j('#preview1').parent().html($j('#preview1').parent().children());
							$j('#preview1').attr('src', e.target.result);
							//$wk_jq("#imageTemplate").tmpl([{'index':i}]).appendTo("#otherimages");
						}
						reader.onloadend  = function(e){
							resizeImageFn('#preview1');
						}
						reader.readAsDataURL(this.files[0]);
					}
				}
		});

	});
//remove	
    $j = jQuery.noConflict();
	var checkAltTextExists = function(id){
		if ($j(id).html().indexOf('Upload an Image')!=-1){
			//alert("already have it");
		}
		else {
			$j(id).prepend("Upload an Image");
		}
	}
    function removeUrl1() {
		checkAltTextExists($j('#preview1').parent());
        $j('#preview1').removeAttr('src');
		$j('#rad1').val('');
    }
	window.onload = function (){
		//jQuery('.multipleSelect').fastselect();
	}
</script>