<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_Stripe
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 * @see        Cryozonic_Stripe_Block_Payment_Info
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php if ($this->getInfo()->getCcType()): ?>
<div class="cryozonic payment-info">
    <?php echo $this->getInfo()->getCcType(); ?> ending <?php echo $this->getInfo()->getCcLast4(); ?>
</div>
<?php endif; ?>

<?php echo $this->getChildHtml()?>
