<?php 
$partner=$this->getProfileDetail();
if($partner->getprofileurl()!=''){
    if(Mage::getStoreConfig('marketplace/seller_profile/activecolorpicker')){?> 
        <style>
        .main{background-image:none;background-color:<?php echo $partner->getBackgroundth();?>;}
        </style>
    <?php
    }
    $_productCollection=$this->getCollection();
    $_helper = $this->helper('catalog/output');
    $helper=Mage::helper('marketplace');
    $partner=$this->getProfileDetail();
    $productname=$this->getRequest()->getParam('name');
    $bannerpic=$partner->getbannerpic()!=''?$partner->getbannerpic():"banner-image.png";
    $bannerpic=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'avatar/'.$bannerpic;
    $today =date('Y-m-d');
    ?>
    <div class="collection-banner"><img src="<?php echo $bannerpic; ?>" alt="no image"></img></div>
    <div class="wk_mp_design" style="padding-top: 10px;">
        <div class="block block-account">   
            <div class="block-title">   
                <strong><span><h4><?php echo $helper->__("SELLER'S COLLECTION") ?></h4></span></strong>
            </div>
        </div>
        <div class="fieldset wk_mp_fieldset" <?php if($_productCollection->count()){ echo 'style="padding: 0;"';}?>>
            <?php if(!$_productCollection->count()): ?>
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
            <?php else: ?>
            <div class="category-products">
                <?php echo $this->getToolbarHtml() ?>
                <?php echo $this->getPagerHtml() ?>
                <?php // List mode ?>
                <?php if($this->getMode()!='grid'): ?>
                <?php $_iterator = 0; ?>
                <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <?php $_imgSize = 300; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <div class="product-primary">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                    <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>
                                </div>
                                <div class="product-secondary">
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                </div>
                                <div class="product-secondary">
                                    <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                        <p class="action"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                    <?php elseif($_product->isSaleable()): ?>
                                        <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                                    <?php else: ?>
                                        <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                        <?php endif; ?>
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
                </ol>
                <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

                <?php else: ?>

                <?php // Grid Mode ?>

                <?php $_collectionSize = $_productCollection->count() ?>
                <?php $_columnCount = $this->getColumnCount(); ?>
                <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                    <?php $i=0; foreach ($_productCollection as $_product): ?>
                        <?php /*if ($i++%$_columnCount==0): ?>
                        <?php endif*/ ?>
                        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php $_imgSize = 210; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                            <div class="product-info">
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>

                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                                <div class="actions">
                                    <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php elseif($_product->isSaleable()): ?>
                                        <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <ul class="add-to-links">
                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                        <?php endif; ?>
                                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                        <?php endif*/ ?>
                    <?php endforeach ?>
                </ul>
                <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
                <?php endif; ?>

                <div class="toolbar-bottom">
                    <?php echo $this->getToolbarHtml() ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/javascript">
        if (typeof jQuery == 'undefined'){
            document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
        }
    </script>
    <script>    
    jQuery.noConflict();
    (function($wk_jq){
        $wk_jq('.toolbar select option').each(function(){
            $url=$wk_jq(this).attr('value').replace('collection/','collection/'+'<?php echo $partner->getprofileurl();?>/');
            $wk_jq(this).attr('value',$url);
        });
        $wk_jq('.toolbar a').each(function(){
            $wk_jq(this).attr('href',$wk_jq(this).attr('href').replace('collection/','collection/'+'<?php echo $partner->getprofileurl();?>/'));
        });
    })(jQuery);

    </script>
<?php } ?>
