<?php
/**
 * Cryozonic
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Single Domain License
 * that is available through the world-wide-web at this URL:
 * http://cryozonic.com/licenses/stripe.html
 * If you are unable to obtain it through the world-wide-web,
 * please send an email to info@cryozonic.com so we can send
 * you a copy immediately.
 *
 * @category   Cryozonic
 * @package    Cryozonic_Stripe
 * @copyright  Copyright (c) Cryozonic Ltd (http://cryozonic.com)
 */

$_code = $this->getMethodCode();
$_addName = !$this->stripe->getSecurityMethod();

echo $this->getLayout()->createBlock('cryozonic_stripe/form_stripeJs')->toHtml();

?>

<?php if ($this->autoDetectCard()): ?>
<style type="text/css">
    <?php foreach ($this->getAcceptedCardTypes() as $code => $label): ?>
    input#cryozonic_stripe_cc_number.cctype-<?php echo $code; ?> { background-image: url(<?php echo $this->getSkinUrl("cryozonic_stripe/img/$code.png"); ?>); }
    <?php endforeach; ?>
</style>
<?php /* We are preloading the images so that there is no lag when they appear */ ?>
<div class="img-preload">
    <?php foreach ($this->getAcceptedCardTypes() as $code => $label): ?>
    <img src="<?php echo $this->getSkinUrl("cryozonic_stripe/img/$code.png"); ?>">
    <?php endforeach; ?>
</div>
<?php endif; ?>

<ul class="form-list stripe-new" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($this->stripe->isApplePayEnabled()): ?>
    <li id="apple-pay-section">
        <button id="apple-pay-button" onlick="beginApplePay();" type="button"></button>
        <div id="payment-request-button"></div>
        <label><?php echo $this->__('Or use a card below'); ?></label>
    </li>
    <li id="apple-pay-result">
        <label><?php echo $this->__('Selected Card'); ?></label>
        <div>
            <span id="apple-pay-result-brand"></span>
            **** <span id="apple-pay-result-last4"></span>
        </div>
        <button type="button" class="button" title="Reset" name="reset" id="apple-pay-reset"><span><span><?php echo $this->__('Reset') ?></span></span></button>
    </li>
    <?php endif; ?>
    <?php echo $this->getLayout()->createBlock('cryozonic_stripe/form_saved')->toHtml(); ?>

    <?php if ($this->showAcceptedCardTypes()): ?>
    <li class="stripe-new">
        <label for="<?php echo $_code ?>_cc_types"><?php echo $this->__('Accepted Card Types') ?></label>
        <div class="input-box" id="cryozonic-stripe-accepted-cards">
            <?php foreach ($this->getAcceptedCardTypes() as $code => $label): ?>
                <img src="<?php echo $this->getSkinUrl("cryozonic_stripe/img/$code.png"); ?>" alt="<?php echo $label; ?>" id="cryozonic_stripe_<?php echo $code; ?>_type" />
            <?php endforeach; ?>
        </div>
    </li>
    <?php endif; ?>

    <?php if ($this->stripe->isStripeElementsEnabled()):

    echo $this->getLayout()->createBlock('cryozonic_stripe/form_stripeElements')->toHtml();

    else: ?>

    <li class="stripe-new">
        <label class="required" for="<?php echo $_code ?>_cc_owner"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required stripe-input input-text" id="<?php echo $_code ?>_cc_owner" <?php if ($_addName): ?>name="payment[cc_owner]" <?php endif; ?>value="<?php echo $this->getInfoData('cc_owner') ?>"/>
        </div>
    </li>
    <li class="stripe-new">
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" <?php if ($_addName): ?>name="payment[cc_number]" <?php endif; ?>title="<?php echo $this->__('Card Number') ?>" class="input-text required stripe-input" value="" <?php echo $this->getOnKeyUpCardNumber(); ?> />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div" class="stripe-new">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" <?php if ($_addName): ?>name="payment[cc_exp_month]" <?php endif; ?>class="month validate-cc-exp required stripe-input">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" <?php if ($_addName): ?>name="payment[cc_exp_year]" <?php endif; ?>class="year required stripe-input">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div" class="stripe-new">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required stripe-input validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" <?php if ($_addName): ?>name="payment[cc_cid]" <?php endif; ?>value="" autocomplete="off" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; // hasVerification() ?>

    <?php endif; // isStripeElementsEnabled() ?>

    <li class="stripe-new" id="cryozonic-stripe-card-errors"></li>

    <?php if ($this->stripe->showSaveCardOption() || $this->stripe->alwaysSaveCard()): ?>
    <li id="<?php echo $_code ?>_cc_save_div" class="stripe-new">
        <div class="input-box">
            <div class="v-fix">
                <label for="<?php echo $_code ?>_cc_save">
                    <?php if ($this->stripe->alwaysSaveCard()): ?>
                        <input type="hidden" class="input-hidden stripe-input" id="<?php echo $_code ?>_cc_save" name="payment[cc_save]" value="1"/>
                    <?php else: ?>
                        <input type="checkbox" title="<?php echo $this->__('Save card for future purchases') ?>" class="input-checkbox stripe-input" id="<?php echo $_code ?>_cc_save" name="payment[cc_save]" checked="checked"/>
                        &nbsp;
                        <?php echo $this->__('Save card for future purchases') ?>
                    <?php endif; ?>
                </label>
            </div>
        </div>
    </li>
    <?php endif; ?>
</ul>
